var games = {
	nes: [ 
		"3-D WorldRunner",
		"8 Eyes",
		"1942",
		"1943: The Battle of Midway",
		"Abadox: The Deadly Inner War",
		"Advanced Dungeons & Dragons: Pool of Radiance",
		"Adventure Island ",
		"Adventure Island II ",
		"Adventure Island III ",
		"Disney Adventures in the Magic Kingdom",
		"Adventures of Lolo",
		"Adventures of Lolo 2",
		"Adventures of Lolo 3",
		"The Adventures of Rad Gravity",
		"Air Fortress",
		"Al Unser Jr. Turbo Racing ",
		"Disney's Aladdin",
		"Alien 3",
		"Arch Rivals: A Basketbrawl!",
		"Archon",
		"Arkanoid",
		"Arkista's Ring",
		"Astyanax ",
		"Bad Dudes ",
		"Bad News Baseball",
		"Balloon Fight",
		"Bandit Kings of Ancient China",
		"The Bard's Tale: Tales of the Unknown",
		"Barker Bill's Trick Shooting",
		"Baseball Simulator 1.000 ",
		"Baseball Stars",
		"Baseball Stars II",
		"Bases Loaded",
		"Bases Loaded II: Second Season",
		"Bases Loaded 3",
		"Bases Loaded 4",
		"Batman: Return of the Joker",
		"Batman: The Video Game",
		"Batman Returns",
		"The Battle of Olympus",
		"Garry Kitchen's Battletank",
		"Battletoads",
		"Battletoads & Double Dragon: The Ultimate Team",
		"Bill Elliott's NASCAR Challenge",
		"Bionic Commando ",
		"The Black Bass USA ",
		"Blades of Steel",
		"Blaster Master",
		"The Blue Marlin",
		"Bomberman",
		"Bomberman II ",
		"Bonk's Adventure",
		"Boulder Dash",
		"David Crane's A Boy and His Blob: Trouble on Blobolonia",
		"BreakThru",
		"Bubble Bobble",
		"Bubble Bobble Part 2",
		"Bucky O'Hare",
		"The Bugs Bunny Birthday Blowout",
		"The Bugs Bunny Crazy Castle",
		"Bump 'n' Jump ",
		"Burai Fighter",
		"BurgerTime",
		"Cabal",
		"Capcom's Gold Medal Challenge '92",
		"Captain America and the Avengers",
		"Captain Skyhawk",
		"Castlevania ",
		"Castlevania II: Simon's Quest ",
		"Castlevania III: Dracula's Curse ",
		"Championship Pool",
		"Championship Rally",
		"The Chessmaster",
		"Disney's Chip 'n Dale Rescue Rangers",
		"Disney's Chip 'n Dale Rescue Rangers 2",
		"City Connection",
		"Clash at Demonhead",
		"Classic Concentration",
		"Clu Clu Land",
		"Cobra Triangle",
		"Code Name: Viper ",
		"Commando",
		"Conflict",
		"Conquest of the Crystal Palace",
		"Contra ",
		"Contra Force ",
		"Cowboy Kid",
		"Crash 'n' the Boys: Street Challenge",
		"Crystalis ",
		"Cyber Stadium Series: Base Wars",
		"Danny Sullivan's Indy Heat",
		"Disney's Darkwing Duck",
		"Deadly Towers",
		"Defender II ",
		"Deja Vu",
		"Demon Sword ",
		"Desert Commander",
		"Destiny of an Emperor ",
		"Devil World",
		"Dig Dug II: Trouble in Paradise",
		"Digger T. Rock: The Legend of the Lost City",
		"Donkey Kong",
		"Donkey Kong: Original Edition",
		"Donkey Kong Jr.",
		"Donkey Kong 3",
		"Double Dragon",
		"Double Dragon II: The Revenge",
		"Double Dragon III: The Sacred Stones",
		"Double Dribble",
		"Dr. Mario",
		"Dragon Fighter",
		"Dragon Spirit: The New Legend",
		"Dragon Warrior ",
		"Dragon Warrior II ",
		"Dragon Warrior III ",
		"Dragon Warrior IV ",
		"Duck Hunt",
		"Disney's DuckTales",
		"Disney's DuckTales 2",
		"Dungeon Magic: Sword of the Elements",
		"Dusty Diamond's All-Star Softball ",
		"EarthBound Beginnings ",
		"Elevator Action",
		"Eliminator Boat Duel",
		"Elite",
		"Excitebike",
		"F-15 Strike Eagle",
		"F-117A Stealth Fighter",
		"Family Feud",
		"Faria: A World of Mystery & Danger!",
		"Faxanadu",
		"Felix the Cat",
		"Ferrari Grand Prix Challenge",
		"Fester's Quest",
		"Final Fantasy",
		"Fire 'n Ice ",
		"Flight of the Intruder ",
		"The Flintstones: The Rescue of Dino & Hoppy",
		"The Flintstones: The Surprise at Dinosaur Peak!",
		"Flying Dragon: The Secret Scroll",
		"Flying Warriors",
		"Formula 1 Sensation ",
		"Formula One: Built to Win",
		"Frankenstein: The Monster Returns",
		"Freedom Force",
		"Friday the 13th",
		"G.I. Joe: A Real American Hero",
		"G.I. Joe: The Atlantis Factor",
		"Galaga: Demons of Death",
		"Galaxy 5000: Racing in the 51st Century",
		"Gargoyle's Quest II: The Demon Darkness",
		"Gauntlet",
		"Gauntlet II",
		"Gemfire ",
		"Genghis Khan",
		"Ghosts 'n Goblins ",
		"Ghoul School",
		"Goal!",
		"Goal! Two",
		"Godzilla: Monster of Monsters!",
		"Golf",
		"Golf Grand Slam",
		"Golgo 13: Top Secret Episode",
		"The Goonies II",
		"Gradius",
		"Gremlins 2: The New Batch",
		"The Guardian Legend ",
		"Guerrilla War",
		"Gumshoe",
		"Gun Nac",
		"Gun.Smoke",
		"Gyromite",
		"Gyruss",
		"Hammerin' Harry ",
		"Hatris",
		"Heavy Barrel",
		"High Speed",
		"Hogan's Alley",
		"Hydlide",
		"Ice Climber",
		"Ice Hockey",
		"Image Fight",
		"The Immortal",
		"The Incredible Crash Dummies",
		"International Cricket",
		"Iron Tank: The Invasion of Normandy ",
		"Isolated Warrior ",
		"Ivan \"Ironman\" Stewart's Super Off Road",
		"Jackal ",
		"Jackie Chan's Action Kung Fu",
		"James Bond Jr.",
		"The Jetsons: Cogswell's Caper!",
		"Jimmy Connors Tennis",
		"Joe & Mac",
		"Journey to Silius ",
		"Joust",
		"Disney's The Jungle Book",
		"Jurassic Park",
		"Kabuki Quantum Fighter",
		"Karnov",
		"Kick Master",
		"Kickle Cubicle",
		"Kid Dracula ",
		"Kid Icarus ",
		"Kid Klown in Night Mayor World ",
		"Kid Niki: Radical Ninja ",
		"Kings of the Beach",
		"King's Quest V: Absence Makes the Heart Go Yonder!",
		"Kirby's Adventure",
		"Kiwi Kraze ",
		"Konami Hyper Soccer",
		"The Krion Conquest ",
		"Kung Fu ",
		"Kung-Fu Heroes ",
		"Laser Invasion ",
		"Legacy of the Wizard ",
		"The Legend of Kage",
		"Legend of the Ghost Lion",
		"The Legend of Zelda",
		"Legendary Wings",
		"Legends of the Diamond: The Baseball Championship Game",
		"Lemmings",
		"L'Empereur",
		"Life Force ",
		"Disney's The Lion King",
		"Little League Baseball: Championship Series",
		"Disney's The Little Mermaid",
		"Little Nemo: The Dream Master",
		"Little Ninja Brothers ",
		"Little Samson",
		"Lode Runner",
		"The Lone Ranger",
		"Loopz",
		"Low G Man: The Low Gravity Man",
		"Lunar Pool",
		"M.C. Kids ",
		"M.U.L.E.",
		"Mach Rider",
		"The Mafat Conspiracy",
		"The Magic of Scheherazade",
		"Magician",
		"Maniac Mansion",
		"Mappy-Land",
		"Marble Madness",
		"Mario Bros.",
		"Mega Man ",
		"Mega Man 2 ",
		"Mega Man 3 ",
		"Mega Man 4 ",
		"Mega Man 5 ",
		"Mega Man 6 ",
		"Mendel Palace ",
		"Metal Gear",
		"Metal Storm",
		"Metroid",
		"Michael Andretti's World GP ",
		"Mickey Mousecapade",
		"Might and Magic Book One: Secret of the Inner Sanctum",
		"Mighty Final Fight",
		"Mike Tyson's Punch-Out!!",
		"Millipede",
		"Milon's Secret Castle",
		"Mission: Impossible",
		"Monopoly",
		"Monster in My Pocket",
		"Monster Party",
		"Mr. Gimmick ",
		"Ms. Pac-Man",
		"NARC",
		"NES Open Tournament Golf ",
		"NES Play Action Football",
		"New Ghostbusters II",
		"Nigel Mansell's World Championship Racing",
		"A Nightmare on Elm Street",
		"Nightshade",
		"Ninja Crusaders",
		"Ninja Gaiden ",
		"Ninja Gaiden II: The Dark Sword of Chaos ",
		"Ninja Gaiden III: The Ancient Ship of Doom",
		"Nintendo World Cup ",
		"Nobunaga's Ambition",
		"Nobunaga's Ambition II",
		"North & South",
		"Operation Wolf",
		"Over Horizon",
		"P.O.W.: Prisoners of War",
		"Pac-Man",
		"Palamedes",
		"Panic Restaurant ",
		"Paperboy",
		"Paperboy 2",
		"Parasol Stars: The Story of Bubble Bobble III",
		"Parodius",
		"Phantom Fighter",
		"Pinball",
		"Pinball Quest",
		"Pin-Bot",
		"Pipe Dream",
		"Pirates!",
		"Popeye",
		"Power Blade ",
		"Power Blade 2 ",
		"Prince of Persia",
		"Princess Tomato in the Salad Kingdom",
		"Pro Sport Hockey ",
		"Pro Wrestling",
		"Punch-Out!!",
		"The Punisher",
		"Puzznic",
		"Q*bert",
		"Qix",
		"R.C. Pro-Am",
		"R.C. Pro-Am II",
		"Alex DeMeo's Race America ",
		"Racket Attack",
		"Rad Racer ",
		"Rad Racer II",
		"Rainbow Islands: The Story of Bubble Bobble 2",
		"Rally Bike",
		"Rampage",
		"Rampart",
		"Renegade ",
		"Rescue: The Embassy Mission",
		"River City Ransom ",
		"Road Fighter",
		"RoadBlasters",
		"Robin Hood: Prince of Thieves",
		"Robo Warrior ",
		"Rock 'n' Ball ",
		"Rockin' Kats",
		"Rod Land",
		"Roller Ball",
		"Rollergames",
		"Romance of the Three Kingdoms",
		"Romance of the Three Kingdoms II",
		"Rush'n Attack ",
		"Rygar ",
		"S.C.A.T.: Special Cybernetic Attack Team ",
		"Section-Z",
		"Seicross",
		"Shadow of the Ninja ",
		"Shadowgate",
		"Shatterhand ",
		"Shingen the Ruler",
		"Shooting Range",
		"Side Pocket",
		"Silk Worm",
		"Skate or Die",
		"Skate or Die 2: The Search for Double Trouble",
		"Sky Kid",
		"Sky Shark",
		"Slalom",
		"Smash T.V.",
		"Snake Rattle 'n' Roll",
		"Snake's Revenge",
		"Snow Bros.",
		"Solar Jetman: Hunt for the Golden Warpship",
		"Solomon's Key",
		"Solstice: The Quest for the Staff of Demnos",
		"Space Shuttle Project",
		"Spelunker",
		"Spot: The Video Game!",
		"Spy Hunter",
		"Spy vs. Spy",
		"Sqoon",
		"Stack-Up ",
		"Stadium Events ",
		"Stanley: The Search for Dr. Livingston",
		"Star Force",
		"Star Soldier",
		"Star Trek: 25th Anniversary",
		"Star Trek: The Next Generation",
		"Star Wars",
		"Star Wars: The Empire Strikes Back",
		"Starship Hector",
		"StarTropics",
		"StarTropics II: Zoda's Revenge",
		"Stinger ",
		"Street Fighter 2010: The Final Fight",
		"Strider",
		"Super C ",
		"Super Dodge Ball ",
		"Super Mario Bros.",
		"Super Mario Bros. 2",
		"Super Mario Bros. 3",
		"Super Spike V'Ball",
		"Super Spy Hunter ",
		"Super Turrican",
		"Sword Master",
		"Swords and Serpents",
		"T&C Surf Designs: Thrilla's Surfari",
		"T&C Surf Designs: Wood & Water Rage",
		"Disney's TaleSpin",
		"Target: Renegade",
		"Tecmo Baseball",
		"Tecmo Bowl",
		"Tecmo Cup Soccer Game",
		"Tecmo NBA Basketball",
		"Tecmo Super Bowl",
		"Tecmo World Cup Soccer",
		"Tecmo World Wrestling",
		"Teenage Mutant Ninja Turtles",
		"Teenage Mutant Ninja Turtles: Tournament Fighters",
		"Teenage Mutant Ninja Turtles II: The Arcade Game",
		"Teenage Mutant Ninja Turtles III: The Manhattan Project",
		"Tennis",
		"Terminator 2: Judgment Day",
		"Terra Cresta",
		"Tetris",
		"Tetris 2 ",
		"The Three Stooges",
		"Thunder & Lightning ",
		"Thunderbirds",
		"Thundercade",
		"Tiger-Heli",
		"Time Lord",
		"Times of Lore",
		"Tiny Toon Adventures",
		"Tiny Toon Adventures 2: Trouble in Wackyland",
		"Toki",
		"Tom and Jerry: The Ultimate Game of Cat and Mouse!",
		"Tombs & Treasure",
		"Top Players' Tennis Featuring Chris Evert & Ivan Lendl",
		"Totally Rad ",
		"Track & Field",
		"Track & Field II",
		"Trog!",
		"Trojan",
		"The Trolls in Crazyland",
		"Twin Cobra ",
		"Twin Eagle: Revenge Joe's Brother",
		"Ufouria: The Saga ",
		"Ultima III: Exodus",
		"Ultima IV: Quest of the Avatar",
		"Ultimate Air Combat ",
		"Uncharted Waters",
		"Uninvited",
		"Urban Champion",
		"Vegas Dream",
		"Vice: Project Doom ",
		"Wacky Races",
		"Wario's Woods",
		"WCW Wrestling ",
		"Werewolf: The Last Warrior",
		"Where in Time Is Carmen Sandiego?",
		"Who Framed Roger Rabbit",
		"Whomp 'Em ",
		"Widget",
		"Wild Gunman",
		"Willow",
		"Wizardry: Knight of Diamonds - The Second Scenario",
		"Wizardry: Proving Grounds of the Mad Overlord",
		"Wizards & Warriors",
		"Wizards & Warriors II: Ironsword",
		"Wizards & Warriors III: Kuros... Visions of Power",
		"Wolverine",
		"World Champ ",
		"Wrecking Crew",
		"Wurm: Journey to the Center of the Earth!",
		"WWF King of the Ring",
		"WWF WrestleMania",
		"WWF WrestleMania Challenge",
		"WWF WrestleMania Steel Cage Challenge",
		"Xevious: The Avenger",
		"Xexyz",
		"Yo! Noid ",
		"Yoshi ",
		"Yoshi's Cookie",
		"The Young Indiana Jones Chronicles",
		"Zanac",
		"Zelda II: The Adventure of Link",
		"Zen: Intergalactic Ninja",
		"Zombie Nation"
	],
	
	snes: [
		"The 7th Saga ",
		"A.S.P.: Air Strike Patrol ",
		"ActRaiser",
		"ActRaiser 2",
		"The Addams Family",
		"Addams Family Values",
		"Advanced Dungeons & Dragons: Eye of the Beholder",
		"The Adventures of Batman & Robin",
		"Aero Fighters ",
		"Aero the Acro-Bat",
		"Aero the Acro-Bat 2",
		"Aerobiz",
		"Aerobiz Supersonic",
		"Disney's Aladdin",
		"Alien 3",
		"Alien vs. Predator",
		"Arcade's Greatest Hits: The Atari Collection 1",
		"Arcana",
		"Ardy Lightfoot",
		"Arkanoid: Doh It Again",
		"Art of Fighting ",
		"Asterix",
		"Axelay",
		"B.O.B.",
		"Bassin's Black Bass with Hank Parker",
		"Batman Returns",
		"Battle Cars",
		"Battle Clash ",
		"Battletoads & Double Dragon: The Ultimate Team",
		"Battletoads in Battlemaniacs",
		"Beavis and Butt-Head",
		"Big Sky Trooper",
		"Biker Mice from Mars",
		"BioMetal",
		"Blackthorne ",
		"BlaZeon: The Bio-Cyborg Challenge",
		"Disney's Bonkers",
		"Boogerman: A Pick and Flick Adventure",
		"Boxing Legends of the Ring ",
		"Brain Lord",
		"Brandish",
		"Brawl Brothers ",
		"Breath of Fire",
		"Breath of Fire II",
		"Bubsy in Claws Encounters of the Furred Kind",
		"Bugs Bunny in Rabbit Rampage",
		"Bulls versus Blazers and the NBA Playoffs",
		"Bust-A-Move ",
		"Cannon Fodder",
		"Captain America and the Avengers",
		"Captain Commando",
		"Castlevania: Dracula X ",
		"Choplifter III",
		"Chrono Trigger",
		"Sid Meier's Civilization",
		"ClayFighter",
		"ClayFighter: Tournament Edition",
		"ClayFighter 2: Judgment Clay",
		"Claymates",
		"Clue",
		"College Slam",
		"The Combatribes",
		"Congo's Caper",
		"Contra III: The Alien Wars ",
		"Cool Spot",
		"Cybernator ",
		"Daffy Duck: The Marvin Missions",
		"Darius Twin",
		"Daze Before Christmas",
		"The Death and Return of Superman",
		"Demolition Man",
		"Demon's Crest",
		"Desert Strike: Return to the Gulf",
		"D-Force",
		"DinoCity",
		"Donkey Kong Country ",
		"Donkey Kong Country Competition Cartridge",
		"Donkey Kong Country 2: Diddy's Kong Quest ",
		"Donkey Kong Country 3: Dixie Kong's Double Trouble! ",
		"Doom",
		"Doom Troopers",
		"Dragon: The Bruce Lee Story",
		"Dragon View ",
		"Drakkhen",
		"Dungeon Master",
		"E.V.O.: Search for Eden",
		"Earth Defense Force ",
		"EarthBound ",
		"Earthworm Jim",
		"Earthworm Jim 2",
		"Elite Soccer ",
		"Equinox ",
		"Extra Innings",
		"F1 Pole Position ",
		"F1 ROC: Race of Champions ",
		"F1 ROC II: Race of Champions ",
		"Faceball 2000",
		"Family Feud",
		"Fatal Fury ",
		"Fatal Fury 2 ",
		"Fatal Fury Special ",
		"FIFA 98: Road to World Cup",
		"FIFA International Soccer",
		"FIFA Soccer 96",
		"FIFA Soccer 97: Gold Edition",
		"Fighter's History",
		"Final Fantasy: Mystic Quest ",
		"Final Fantasy II ",
		"Final Fantasy III ",
		"Final Fight",
		"Final Fight 2",
		"Final Fight 3",
		"Final Fight Guy",
		"The Firemen",
		"Firepower 2000 ",
		"Firestriker",
		"Flashback: The Quest for Identity",
		"The Flintstones: The Treasure of Sierra Madrock",
		"Frogger",
		"F-Zero",
		"Gemfire ",
		"Genghis Khan II: Clan of the Gray Wolf",
		"Ghoul Patrol",
		"Gods",
		"Disney's Goof Troop",
		"Gradius III",
		"The Great Circus Mystery Starring Mickey & Minnie ",
		"Hagane: The Final Conflict",
		"HAL's Hole in One Golf",
		"Harvest Moon",
		"Hebereke's Popoon",
		"Hook",
		"Hurricanes",
		"Hyper V-Ball ",
		"Hyper Zone",
		"The Ignition Factor ",
		"Illusion of Gaia ",
		"Imperium",
		"The Incredible Hulk",
		"Indiana Jones' Greatest Adventure",
		"Inindo: Way of the Ninja",
		"International Superstar Soccer",
		"International Superstar Soccer Deluxe",
		"Jelly Boy",
		"The Jetsons: Invasion of the Planet Pirates",
		"Jimmy Connors Pro Tennis Tour",
		"Joe & Mac",
		"Joe & Mac 2: Lost in the Tropics",
		"John Madden Football",
		"John Madden Football '93",
		"Judge Dredd",
		"Disney's The Jungle Book",
		"Jungle Strike: The Sequel to Desert Strike",
		"Jurassic Park",
		"Jurassic Park Part 2: The Chaos Continues",
		"Justice League Task Force",
		"Ken Griffey Jr. Presents Major League Baseball",
		"Ken Griffey Jr.'s Winning Run",
		"Kendo Rage",
		"Kid Klown in Crazy Chase",
		"Killer Instinct",
		"King Arthur's World ",
		"The King of Dragons",
		"King of the Monsters",
		"King of the Monsters 2",
		"Kirby Super Star ",
		"Kirby's Avalanche ",
		"Kirby's Dream Course ",
		"Kirby's Dream Land 3",
		"Knights of the Round",
		"Lagoon",
		"Lamborghini American Challenge",
		"Legend",
		"The Legend of the Mystical Ninja ",
		"The Legend of Zelda: A Link to the Past",
		"Lemmings",
		"Lemmings 2: The Tribes",
		"Lethal Enforcers",
		"Liberty or Death",
		"The Lion King",
		"Looney Tunes B-Ball",
		"The Lost Vikings",
		"The Lost Vikings 2",
		"Lucky Luke",
		"Lufia & The Fortress of Doom",
		"Lufia II: Rise of the Sinistrals",
		"Madden NFL '94",
		"Madden NFL 95",
		"Madden NFL 96",
		"Madden NFL 97",
		"Madden NFL 98",
		"Magic Sword",
		"The Magical Quest Starring Mickey Mouse",
		"Mario Paint",
		"Mark Davis' The Fishing Master",
		"Marvel Super Heroes in War of the Gems",
		"The Mask",
		"Maui Mallard in Cold Shadow ",
		"Mecarobot Golf",
		"MechWarrior ",
		"MechWarrior 3050 ",
		"Mega Man 7 ",
		"Mega Man Soccer ",
		"Mega Man X ",
		"Mega Man X2 ",
		"Mega Man X3 ",
		"Metal Combat: Falcon's Revenge",
		"Metal Marines ",
		"Metal Warriors",
		"Michael Jordan: Chaos in the Windy City",
		"Mickey Mania: The Timeless Adventures of Mickey Mouse",
		"Mickey's Ultimate Challenge",
		"Micro Machines",
		"Micro Machines 2: Turbo Tournament",
		"Might and Magic II: Gates to Another World",
		"Might and Magic III: Isles of Terra",
		"Mighty Morphin Power Rangers",
		"Mighty Morphin Power Rangers: The Fighting Edition",
		"Mighty Morphin Power Rangers: The Movie",
		"MLBPA Baseball",
		"Mohawk & Headphone Jack",
		"Monopoly",
		"Mortal Kombat",
		"Mortal Kombat II",
		"Mortal Kombat 3",
		"Mr. Do!",
		"Mr. Nutz",
		"Ms. Pac-Man",
		"Natsume Championship Wrestling",
		"NBA Give 'n Go",
		"NBA Hang Time",
		"NBA Jam",
		"NBA Jam: Tournament Edition",
		"NBA Live 95",
		"NBA Live 96",
		"NBA Live 97",
		"NBA Live 98",
		"NBA Showdown",
		"NCAA Basketball ",
		"NFL Quarterback Club",
		"NFL Quarterback Club 96",
		"NHL '94",
		"NHL 95",
		"NHL 96",
		"NHL 97",
		"NHL 98",
		"NHL Stanley Cup ",
		"NHLPA Hockey 93",
		"Ninja Gaiden Trilogy",
		"The Ninja Warriors",
		"Nobunaga's Ambition",
		"Nobunaga's Ambition II: Lord of Darkness",
		"Nosferatu",
		"Ogre Battle: The March of the Black Queen",
		"On the Ball ",
		"Operation Europe: Path to Victory 1939-45",
		"Operation Logic Bomb: The Ultimate Search & Destroy ",
		"Out of This World ",
		"Out to Lunch (Pierre le Chef is... Out to Lunch)",
		"P.T.O.: Pacific Theater of Operations",
		"P.T.O. II: Pacific Theater of Operations",
		"Pac-Attack",
		"Pac-Man 2: The New Adventures",
		"Paladin's Quest ",
		"Paperboy 2",
		"The Peace Keepers ",
		"PGA Tour 96",
		"Phalanx",
		"Phantom 2040",
		"Pieces ",
		"Pilotwings",
		"Pinball Dreams",
		"Pinball Fantasies",
		"The Pirates of Dark Water",
		"Pitfall: The Mayan Adventure",
		"Plok!",
		"Pocky & Rocky ",
		"Pocky & Rocky 2 ",
		"Pop'n TwinBee",
		"Populous",
		"Populous II: Trials of the Olympian Gods",
		"Power Drive",
		"Power Instinct ",
		"Power Monger",
		"Power Rangers Zeo: Battle Racers",
		"Prehistorik Man",
		"Primal Rage",
		"Prince of Persia",
		"Pro Sport Hockey ",
		"Push-Over",
		"Q*bert 3",
		"Raiden Trad ",
		"Rampart",
		"Ranma 1/2: Hard Battle",
		"Realm",
		"Riddick Bowe Boxing ",
		"Rise of the Phoenix",
		"Rival Turf! ",
		"RoboCop versus The Terminator",
		"Robotrek ",
		"Rock n' Roll Racing",
		"Rocky Rodent ",
		"Romance of the Three Kingdoms II",
		"Romance of the Three Kingdoms III: Dragon of Destiny",
		"Romance of the Three Kingdoms IV: Wall of Fire",
		"R-Type III: The Third Lightning",
		"Run Saber",
		"Samurai Shodown ",
		"Saturday Night Slam Masters ",
		"Scooby-Doo Mystery",
		"Secret of Evermore",
		"Secret of Mana ",
		"Shadowrun",
		"Shanghai II: Dragon's Eye",
		"Shaq-Fu",
		"Shien's Revenge ",
		"Side Pocket",
		"SimAnt: The Electronic Ant Colony",
		"SimCity",
		"SimCity 2000",
		"The Simpsons: Bart's Nightmare",
		"Sink or Swim ",
		"Skyblazer",
		"Smart Ball ",
		"Smash Tennis ",
		"The Smurfs",
		"The Smurfs Travel the World",
		"Snow White in Happily Ever After",
		"Soldiers of Fortune ",
		"Sonic Blast Man",
		"Sonic Blast Man II",
		"SOS ",
		"Soul Blazer",
		"Space Invaders: The Original Game",
		"Space Megaforce ",
		"Spanky's Quest",
		"Sparkster ",
		"Todd McFarlane's Spawn: The Video Game",
		"Spider-Man: The Animated Series",
		"Spider-Man and the X-Men in Arcade's Revenge",
		"Spider-Man and Venom: Maximum Carnage",
		"Spider-Man and Venom: Separation Anxiety",
		"Spindizzy Worlds",
		"Sports Illustrated: Championship Football & Baseball",
		"Star Fox ",
		"Star Fox 2",
		"Star Trek: Deep Space Nine - Crossroads of Time",
		"Star Trek: Starfleet Academy - Starship Bridge Simulator",
		"Stone Protectors",
		"Street Fighter Alpha 2",
		"Street Fighter II: The World Warrior",
		"Street Fighter II Turbo: Hyper Fighting",
		"Street Racer",
		"Strike Gunner S.T.G.",
		"Stunt Race FX ",
		"Sunset Riders",
		"Super Adventure Island ",
		"Super Adventure Island II ",
		"Super Baseball 2020",
		"Super Baseball Simulator 1.000 ",
		"Super Bases Loaded",
		"Super Bases Loaded 2",
		"Super Bases Loaded 3: License to Steal",
		"Super Batter Up",
		"Garry Kitchen's Super Battletank",
		"Super Battletank 2",
		"Super Black Bass",
		"Super Bomberman",
		"Super Bomberman 2",
		"Super Bomberman 3",
		"Super Bonk ",
		"Super Buster Bros. ",
		"Super Castlevania IV",
		"Super Chase H.Q.",
		"Super Conflict: The Mideast",
		"Super Double Dragon ",
		"Super Ghouls 'n Ghosts ",
		"Super Godzilla",
		"Super International Cricket",
		"Super Mario All-Stars",
		"Super Mario Kart",
		"Super Mario RPG: Legend of the Seven Stars",
		"Super Mario World ",
		"Super Mario World 2: Yoshi's Island",
		"Super Metroid",
		"Super Ninja Boy ",
		"Super Nova ",
		"Super Off Road",
		"Super Pinball: Behind the Mask",
		"Super Punch-Out!!",
		"Super Putty",
		"Super R.B.I. Baseball",
		"Super R-Type",
		"Super Smash T.V.",
		"Super Soccer",
		"Super Soccer Champ",
		"Super Star Fox Weekend: Official Competition",
		"Super Star Wars",
		"Super Star Wars: Return of the Jedi",
		"Super Star Wars: The Empire Strikes Back",
		"Super Street Fighter II: The New Challengers",
		"Super Strike Eagle",
		"Super Tennis",
		"Super Troll Islands",
		"Super Turrican",
		"Super Turrican 2",
		"Super Valis IV",
		"Super Widget",
		"SWAT Kats: The Radical Squadron",
		"Syndicate",
		"Temco Secret of the Stars ",
		"Tecmo Super Baseball",
		"Tecmo Super Bowl",
		"Tecmo Super Bowl II: Special Edition",
		"Tecmo Super Bowl III: Final Edition",
		"Tecmo Super NBA Basketball",
		"Teenage Mutant Ninja Turtles: Tournament Fighters",
		"Teenage Mutant Ninja Turtles IV: Turtles in Time",
		"Terranigma",
		"Test Drive II: The Duel",
		"Tetris & Dr. Mario",
		"Tetris 2",
		"Tetris Attack ",
		"Theme Park",
		"Thunder Spirits",
		"Tin Star",
		"Tiny Toon Adventures: Buster Busts Loose!",
		"Tiny Toon Adventures: Wacky Sports Challenge",
		"Top Gear",
		"Top Gear 2",
		"Top Gear 3000",
		"Total Carnage",
		"Disney's Toy Story",
		"Trials of Mana ",
		"Troddlers",
		"True Golf Classics: Pebble Beach Golf Links",
		"True Golf Classics: Waialae Country Club",
		"True Golf Classics: Wicked 18",
		"True Lies",
		"Tuff E Nuff ",
		"Turn and Burn: No-Fly Zone ",
		"The Twisted Tales of Spike McFang",
		"U.N. Squadron ",
		"Ultima: Runes of Virtue II",
		"Ultima VI: The False Prophet",
		"Ultima VII: The Black Gate",
		"Ultimate Mortal Kombat 3",
		"Uncharted Waters",
		"Uncharted Waters: New Horizons",
		"Uniracers ",
		"The Untouchables",
		"Urban Strike: The Sequel to Jungle Strike",
		"Utopia: The Creation of a Nation",
		"Vegas Stakes",
		"Vortex",
		"War 2410",
		"War 3010: The Revolution",
		"Wario's Woods",
		"WCW SuperBrawl Wrestling",
		"Weaponlord",
		"Where in the World Is Carmen Sandiego?",
		"Whirlo ",
		"Wild Guns",
		"Wild Snake ",
		"Jim Lee's WildC.A.T.s: Covert Action Teams",
		"Williams Arcade's Greatest Hits",
		"Wing Commander",
		"Wing Commander: The Secret Missions",
		"Winter Gold",
		"Winter Olympic Games: Lillehammer '94",
		"Wizardry V: Heart of the Maelstrom ",
		"Wolfchild",
		"Wolfenstein 3D",
		"Wolverine: Adamantium Rage",
		"Wordtris",
		"World Cup USA 94 ",
		"World Heroes",
		"World Heroes 2",
		"World Soccer '94: Road to Glory",
		"Worms",
		"WWF Raw",
		"WWF Royal Rumble",
		"WWF Super WrestleMania",
		"WWF WrestleMania: The Arcade Game",
		"Xardion",
		"X-Kaliber 2097 ",
		"X-Men: Mutant Apocalypse",
		"Yoshi's Cookie",
		"Yoshi's Safari ",
		"Young Merlin",
		"Ys III: Wanderers from Ys",
		"Zero the Kamikaze Squirrel",
		"Zombies Ate My Neighbors ",
		"Zool: Ninja of the \"Nth\" Dimension"
	],
	
	n64: [
		"007: The World Is Not Enough",
		"1080° Snowboarding",
		"Aero Fighters Assault ",
		"Aidyn Chronicles: The First Mage",
		"All-Star Baseball 99",
		"All-Star Baseball 2000",
		"All-Star Baseball 2001",
		"Army Men: Air Combat",
		"Army Men: Sarge's Heroes",
		"Army Men: Sarge's Heroes 2",
		"Banjo-Kazooie",
		"Banjo-Tooie",
		"BattleTanx",
		"BattleTanx: Global Assault",
		"Battlezone: Rise of the Black Dogs",
		"Beetle Adventure Racing!",
		"Blast Corps",
		"Body Harvest",
		"Bomberman 64",
		"Bomberman 64: The Second Attack!",
		"Bomberman Hero",
		"Bust-A-Move '99 ",
		"Bust-A-Move 2: Arcade Edition",
		"Castlevania",
		"Castlevania: Legacy of Darkness",
		"Chameleon Twist",
		"Chameleon Twist 2",
		"Charlie Blast's Territory",
		"ClayFighter: Sculptor's Cut",
		"Command & Conquer",
		"Conker's Bad Fur Day",
		"Cruis'n Exotica",
		"Cruis'n USA",
		"Cruis'n World",
		"Destruction Derby 64",
		"Diddy Kong Racing",
		"Donkey Kong 64",
		"Doom 64",
		"Dr. Mario 64",
		"Duck Dodgers Starring Daffy Duck",
		"Duke Nukem: Zero Hour",
		"Duke Nukem 64",
		"Earthworm Jim 3D",
		"ECW Hardcore Revolution",
		"Excitebike 64",
		"Extreme-G",
		"Extreme-G 2",
		"F-1 World Grand Prix",
		"F-1 World Grand Prix II",
		"FIFA 98: Road to World Cup",
		"FIFA 99",
		"FIFA Soccer 64",
		"Fighter Destiny 2",
		"Fighters Destiny",
		"Fighting Force 64",
		"Flying Dragon",
		"Forsaken 64",
		"F-Zero X",
		"Gauntlet Legends",
		"Gex 3: Deep Cover Gecko",
		"Gex 64: Enter the Gecko",
		"Glover",
		"Goemon's Great Adventure ",
		"Golden Nugget 64",
		"GoldenEye 007",
		"Harvest Moon 64",
		"Hexen",
		"Hey You, Pikachu!",
		"Hot Wheels Turbo Racing",
		"Hybrid Heaven",
		"Hydro Thunder",
		"Iggy's Reckin' Balls",
		"Indiana Jones and the Infernal Machine",
		"Indy Racing 2000",
		"International Superstar Soccer 64",
		"International Superstar Soccer '98",
		"International Superstar Soccer 2000",
		"International Track & Field 2000 ",
		"Jeopardy!",
		"Jet Force Gemini ",
		"Ken Griffey Jr.'s Slugfest",
		"Killer Instinct Gold",
		"Kirby 64: The Crystal Shards",
		"Knife Edge: Nose Gunner",
		"Knockout Kings 2000",
		"Kobe Bryant in NBA Courtside",
		"The Legend of Zelda: Majora's Mask",
		"The Legend of Zelda: Ocarina of Time",
		"The Legend of Zelda: Ocarina of Time - Master Quest",
		"LEGO Racers",
		"Lode Runner 3-D",
		"Mace: The Dark Age",
		"Madden Football 64",
		"Madden NFL 99",
		"Madden NFL 2000",
		"Madden NFL 2001",
		"Madden NFL 2002",
		"Magical Tetris Challenge",
		"Major League Baseball Featuring Ken Griffey Jr.",
		"Mario Golf",
		"Mario Kart 64",
		"Mario Party",
		"Mario Party 2",
		"Mario Party 3",
		"Mario Tennis",
		"Mega Man 64 ",
		"Mickey's Speedway USA",
		"Micro Machines 64 Turbo",
		"Midway's Greatest Arcade Hits: Volume 1",
		"Mischief Makers",
		"Mission: Impossible",
		"Monaco Grand Prix",
		"Monster Truck Madness 64",
		"Mortal Kombat 4",
		"Mortal Kombat Mythologies: Sub-Zero",
		"Mortal Kombat Trilogy",
		"Ms. Pac-Man: Maze Madness",
		"Mystical Ninja Starring Goemon",
		"Namco Museum 64",
		"NBA Courtside 2 Featuring Kobe Bryant",
		"NBA Hang Time",
		"NBA In the Zone 2000",
		"NBA Jam 99",
		"NBA Jam 2000",
		"NBA Live 99",
		"NBA Live 2000",
		"NBA Showtime: NBA on NBC",
		"The New Tetris",
		"NFL Blitz",
		"NFL Blitz: Special Edition",
		"NFL Blitz 2000",
		"NFL Blitz 2001",
		"NFL Quarterback Club 98",
		"NFL Quarterback Club 99",
		"NHL 99",
		"Nightmare Creatures",
		"Nuclear Strike 64",
		"Ogre Battle 64: Person of Lordly Caliber",
		"Paper Mario ",
		"Penny Racers ",
		"Perfect Dark",
		"Pilotwings 64",
		"Pokemon Puzzle League",
		"Pokemon Snap",
		"Pokemon Stadium",
		"Pokemon Stadium 2",
		"Quake",
		"Quake II",
		"Quest 64 ",
		"Rampage 2: Universal Tour",
		"Rampage World Tour",
		"Rayman 2: The Great Escape",
		"Ready 2 Rumble Boxing",
		"Ready 2 Rumble Boxing: Round 2",
		"Resident Evil 2 ",
		"Re-Volt",
		"Ridge Racer 64",
		"Road Rash 64",
		"Robotron 64 ",
		"Rocket: Robot on Wheels",
		"Rush 2: Extreme Racing USA",
		"San Francisco Rush: Extreme Racing",
		"San Francisco Rush 2049",
		"Shadow Man",
		"Shadowgate 64: Trails of the Four Towers",
		"Snowboard Kids",
		"Snowboard Kids 2",
		"South Park",
		"South Park Rally",
		"Space Invaders ",
		"Space Station Silicon Valley",
		"Spider-Man",
		"Star Fox 64 ",
		"Star Soldier: Vanishing Earth",
		"Star Wars: Rogue Squadron",
		"Star Wars: Shadows of the Empire",
		"Star Wars Episode I: Battle for Naboo",
		"Star Wars Episode I: Racer",
		"StarCraft 64",
		"Stunt Racer 64",
		"Super Mario 64",
		"Super Smash Bros.",
		"Disney's Tarzan",
		"Tetrisphere",
		"Tigger's Honey Hunt",
		"Tom Clancy's Rainbow Six",
		"Tonic Trouble",
		"Tony Hawk's Pro Skater",
		"Tony Hawk's Pro Skater 2",
		"Tony Hawk's Pro Skater 3",
		"Top Gear Hyper-Bike",
		"Top Gear Overdrive",
		"Top Gear Rally",
		"Top Gear Rally 2",
		"Disney-Pixar Toy Story 2: Buzz Lightyear to the Rescue!",
		"Triple Play 2000",
		"Turok: Dinosaur Hunter",
		"Turok: Rage Wars",
		"Turok 2: Seeds of Evil",
		"Turok 3: Shadow of Oblivion",
		"Vigilante 8",
		"Vigilante 8: 2nd Offense",
		"Virtual Pool 64",
		"Wave Race 64",
		"Wayne Gretzky's 3D Hockey",
		"Wayne Gretzky's 3D Hockey '98",
		"WCW Backstage Assault",
		"WCW Mayhem",
		"WCW Nitro",
		"WCW vs. nWo: World Tour",
		"WCW/nWo Revenge",
		"Wetrix",
		"Wheel of Fortune",
		"WinBack: Covert Operations",
		"Wipeout 64",
		"World Cup 98",
		"World Driver Championship",
		"Worms Armageddon",
		"WWF Attitude",
		"WWF No Mercy",
		"WWF War Zone",
		"WWF WrestleMania 2000",
		"Yoshi's Story"
	],
	
	gb: [
		"Adventure Island ",
		"Adventure Island II: Aliens in Paradise ",
		"Adventures of Lolo",
		"The Adventures of Star Saver",
		"Aerostar",
		"Disney's Aladdin",
		"Alfred Chicken",
		"Alleyway",
		"All-Star Baseball 99",
		"Amazing Penguin",
		"Amazing Tater ",
		"Arcade Classic No. 1: Asteroids & Missile Command",
		"Arcade Classic No. 2: Centipede & Millipede",
		"Arcade Classic No. 3: Galaga & Galaxian",
		"Arcade Classic No. 4: Defender & Joust",
		"Arcade Classics: Super Breakout & Battlezone",
		"Asterix",
		"Asterix & Obelix",
		"Asteroids",
		"Atomic Punk ",
		"Avenging Spirit ",
		"Balloon Kid",
		"Bases Loaded",
		"Batman: Return of the Joker",
		"Batman: The Animated Series",
		"Batman: The Video Game",
		"Battle Arena Toshinden",
		"The Battle of Olympus",
		"Battle Unit Zeoth",
		"Battleship: The Classic Naval Combat Game",
		"Battletoads",
		"Battletoads & Double Dragon: The Ultimate Team",
		"Battletoads in Ragnarok's World",
		"Beavis and Butt-Head",
		"Bill Elliott's NASCAR Fast Tracks",
		"Bionic Battler",
		"Bionic Commando",
		"Black Bass: Lure Fishing",
		"Blades of Steel",
		"Blaster Master Boy",
		"Bomb Jack",
		"Bomberman GB",
		"Bonk's Adventure ",
		"Bonk's Revenge ",
		"Boulder Dash",
		"Boxxle ",
		"Boxxle II ",
		"Brain Drain",
		"BreakThru!",
		"Bubble Bobble",
		"Bubble Bobble Part 2",
		"Bubble Ghost",
		"The Bugs Bunny Crazy Castle",
		"The Bugs Bunny Crazy Castle 2",
		"Burai Fighter Deluxe",
		"BurgerTime Deluxe",
		"Bust-A-Move 2: Arcade Edition ",
		"Bust-A-Move 3 DX",
		"Buster Bros. ",
		"Castle Quest",
		"Castlevania: The Adventure",
		"Castlevania II: Belmont's Revenge",
		"Castlevania Legends",
		"Catrap ",
		"Championship Pool",
		"Chase H.Q.",
		"Choplifter II",
		"Choplifter III",
		"College Slam",
		"Contra: The Alien Wars ",
		"Cool Ball ",
		"Cool Spot",
		"Cosmo Tank",
		"Cyraid ",
		"Daedalian Opus",
		"Daffy Duck",
		"Disney's Darkwing Duck",
		"Dead Heat Scramble",
		"Desert Strike: Return to the Gulf",
		"Dexterity",
		"Dig Dug",
		"Donkey Kong",
		"Donkey Kong Land",
		"Donkey Kong Land 2",
		"Donkey Kong Land III",
		"Double Dragon",
		"Double Dragon II",
		"Double Dragon 3: The Arcade Game",
		"Double Dribble: 5-on-5",
		"Dr. Franken",
		"Dr. Franken II",
		"Dr. Mario",
		"Disney's DuckTales",
		"Disney's DuckTales 2",
		"Earthworm Jim",
		"Elevator Action",
		"F1 Pole Position",
		"F-1 Race",
		"F-15 Strike Eagle",
		"Faceball 2000",
		"Felix the Cat",
		"Ferrari Grand Prix Challenge",
		"FIFA 98: Road to World Cup",
		"FIFA Soccer 97",
		"Fighting Simulator: 2-in-1 Flying Warriors",
		"Final Fantasy Adventure ",
		"The Final Fantasy Legend ",
		"Final Fantasy Legend II ",
		"Final Fantasy Legend III ",
		"Fire Fighter",
		"Fish Dude",
		"The Flash",
		"The Flintstones: King Rock Treasure Island",
		"Flipull",
		"Fortified Zone ",
		"Frogger",
		"Game & Watch Gallery",
		"Gargoyle's Quest ",
		"Gauntlet II",
		"Gear Works",
		"Ghostbusters II",
		"Golf",
		"Gradius: The Interstellar Assault ",
		"Great Greed",
		"HAL Wrestling ",
		"Hammerin' Harry: Ghost Building Company",
		"Harvest Moon GB",
		"Hatris",
		"Heiankyo Alien",
		"High Speed II: The Getaway",
		"High Stakes Gambling",
		"Hit the Ice",
		"Hook",
		"Disney's The Hunchback of Notre Dame: 5 Foolishly Fun Topsy Turvy Games",
		"The Hunt for Red October",
		"Hyper Lode Runner",
		"In Your Face",
		"International Superstar Soccer",
		"Iron Man and X-O Manowar in Heavy Metal",
		"Ishido: The Way of Stones",
		"Jack Nicklaus Golf",
		"James Bond 007",
		"The Jetsons: Robot Panic",
		"Jimmy Connors Tennis",
		"Joe & Mac",
		"Disney's The Jungle Book",
		"Jungle Strike: The Sequel to Desert Strike",
		"Jurassic Park",
		"Jurassic Park Part 2: The Chaos Continues",
		"Ken Griffey Jr. Presents Major League Baseball",
		"Kid Dracula ",
		"Kid Icarus: Of Myths and Monsters",
		"Killer Instinct",
		"The King of Fighters 95",
		"The King of Fighters: Heat of Battle",
		"Kingdom Crusade ",
		"Kirby's Block Ball",
		"Kirby's Dream Land",
		"Kirby's Dream Land 2",
		"Kirby's Pinball Land",
		"Kirby's Star Stacker ",
		"Klax",
		"Knight Quest",
		"Kung-Fu Master ",
		"Kwirk: He's A-maze-ing!",
		"Lamborghini American Challenge",
		"Legend of the River King GB ",
		"The Legend of Zelda: Link's Awakening",
		"Lemmings",
		"Lemmings 2: The Tribes",
		"The Lion King",
		"Disney's The Little Mermaid",
		"Lock 'n' Chase",
		"Looney Tunes",
		"Loopz",
		"The Lost World: Jurassic Park",
		"Lucky Luke",
		"Lucle",
		"Madden NFL 95",
		"Madden NFL 96",
		"Madden NFL 97",
		"Marble Madness",
		"Mario's Picross",
		"Maru's Mission",
		"Maui Mallard in Cold Shadow",
		"Mega Man: Dr. Wily's Revenge ",
		"Mega Man II ",
		"Mega Man III ",
		"Mega Man IV ",
		"Mega Man V ",
		"Megalit",
		"Mercenary Force",
		"Metal Masters",
		"Metroid II: Return of Samus",
		"Mickey Mouse: Magic Wands!",
		"Mickey's Dangerous Chase",
		"Mickey's Ultimate Challenge",
		"Micro Machines",
		"Micro Machines 2: Turbo Tournament",
		"Mighty Morphin Power Rangers",
		"Mighty Morphin Power Rangers: The Movie",
		"Milon's Secret Castle",
		"Miner 2049er Starring Bounty Bob",
		"Missile Command",
		"Mole Mania",
		"Monopoly",
		"Monster Max",
		"Monster Truck Wars",
		"Mortal Kombat",
		"Mortal Kombat II",
		"Mortal Kombat 3",
		"Motocross Maniacs",
		"Mr. Chin's Gourmet Paradise",
		"Mr. Do!",
		"Mr. Nutz",
		"Ms. Pac-Man",
		"Mysterium",
		"Mystical Ninja Starring Goemon",
		"NBA All-Star Challenge",
		"NBA All-Star Challenge 2",
		"NBA Jam",
		"NBA Jam: Tournament Edition",
		"NBA Live 96",
		"Nemesis ",
		"NFL Quarterback Club 96",
		"Nigel Mansell's World Championship Racing",
		"Ninja Boy ",
		"Ninja Boy 2 ",
		"Ninja Gaiden Shadow ",
		"Ninja Taro",
		"Nintendo World Cup ",
		"Nobunaga's Ambition",
		"Oddworld Adventures",
		"Olympic Summer Games",
		"Operation C ",
		"Pac-Attack",
		"Pac-In-Time",
		"Pac-Man",
		"Paperboy",
		"Paperboy 2",
		"Parasol Stars: Rainbow Islands II",
		"Parodius",
		"Penguin Wars",
		"PGA European Tour",
		"PGA Tour 96",
		"Pinball Dreams",
		"Pinball Fantasies",
		"Pipe Dream",
		"Pokemon Blue Version ",
		"Pokemon Red Version ",
		"Pokemon Yellow Version: Special Pikachu Edition ",
		"Popeye 2",
		"Pop'n TwinBee",
		"Power Racer ",
		"Primal Rage",
		"Prince of Persia",
		"Pyramids of Ra",
		"Q*bert",
		"Qix",
		"Quarth",
		"Race Drivin'",
		"Radar Mission",
		"Rampart",
		"The Real Ghostbusters ",
		"David Crane's The Rescue of Princess Blobette",
		"Revenge of the 'Gator",
		"Road Rash",
		"RoboCop",
		"Rod Land",
		"Rolan's Curse",
		"Rolan's Curse 2",
		"R-Type",
		"R-Type II",
		"Samurai Shodown ",
		"Sea Battle",
		"Sensible Soccer: European Champions",
		"Serpent",
		"Shanghai",
		"Shaq-Fu",
		"Side Pocket",
		"Skate or Die: Bad 'n Rad",
		"The Smurfs",
		"The Smurfs Travel the World",
		"Snoopy's Magic Show",
		"Snow Brothers",
		"Solar Striker",
		"Solitaire FunPak",
		"Solomon's Club",
		"Space Invaders",
		"Spanky's Quest",
		"Speedy Gonzales",
		"Sports Illustrated: Championship Football & Baseball",
		"Sports Illustrated: Golf Classic",
		"Star Hawk",
		"Star Trek: 25th Anniversary",
		"Star Trek: The Next Generation",
		"Star Wars",
		"Star Wars: The Empire Strikes Back",
		"Stop That Roach!",
		"Street Fighter II: The World Warrior",
		"Street Racer",
		"Sumo Fighter",
		"Super Battletank: War in the Gulf",
		"Super Black Bass",
		"Super Chase H.Q.",
		"Super Hunchback",
		"Super Mario Land",
		"Super Mario Land 2: 6 Golden Coins",
		"Super Mario Land 3: Wario Land",
		"Super Off Road",
		"Super R.C. Pro-Am",
		"Super Scrabble",
		"Super Star Wars: Return of the Jedi",
		"The Sword of Hope ",
		"The Sword of Hope II ",
		"Tail 'Gator ",
		"Disney's TaleSpin",
		"Tamagotchi",
		"Taz-Mania",
		"Tecmo Bowl",
		"Teenage Mutant Ninja Turtles: Fall of the Foot Clan",
		"Teenage Mutant Ninja Turtles II: Back from the Sewers",
		"Teenage Mutant Ninja Turtles III: Radical Rescue",
		"Tennis",
		"Tesserae",
		"Tetris",
		"Tetris 2",
		"Tetris Attack",
		"Tetris Blast",
		"Tetris Plus",
		"Tiny Toon Adventures: Babs' Big Breka",
		"Tiny Toon Adventures: Wacky Sports Challenge",
		"Tiny Toon Adventures 2: Montana's Movie Madness",
		"Tom and Jerry",
		"Tom and Jerry: Frantic Antics!",
		"Top Rank Tennis",
		"Disney's Toy Story",
		"Track & Field",
		"Trax",
		"Trip World",
		"True Lies",
		"Tumble Pop",
		"Turok: Battle of the Binosaurs",
		"Turrican",
		"Ultima: Runes of Virtue",
		"Ultima: Runes of Virtue II",
		"Universal Soldier",
		"Urban Strike: The Sequel to Jungle Strike",
		"Vegas Stakes",
		"V-Rally: Championship Edition",
		"Wario Blast Featuring Bomberman!",
		"Wario Land II",
		"Wave Race",
		"WCW: The Main Event",
		"Who Framed Roger Rabbit",
		"Wild Snake",
		"Winter Olympic Games: Lillehammer '94",
		"Wizards & Warriors X: Fortress of Fear",
		"Word Zap",
		"Wordtris",
		"World Cup '98",
		"World Heroes 2 Jet",
		"Worms",
		"WWF King of the Ring",
		"WWF Superstars",
		"WWF Superstars 2",
		"WWF War Zone",
		"Xenon 2: Megablast",
		"Yoshi ",
		"Yoshi's Cookie",
		"Zen: Intergalactic Ninja",
		"Zool: Ninja of the \"Nth\" Dimension",
		"Zoop"
	],
	
	gbc: [
		"1942",
		"Disney's Aladdin",
		"Walt Disney's Alice in Wonderland",
		"Aliens: Thanatos Encounter",
		"Alone in the Dark: The New Nightmare",
		"Armorines: Project S.W.A.R.M.",
		"Army Men",
		"Army Men: Air Combat",
		"Army Men: Serge's Heroes 2",
		"Army Men 2",
		"Asterix: Search for Dogmatix ",
		"Asterix & Obelix",
		"Asteroids",
		"Azure Dreams",
		"Ballistic",
		"Batman: Chaos in Gotham",
		"Battleship: The Classic Naval Combat Game",
		"BattleTanx",
		"Bionic Commando: Elite Forces",
		"Blade",
		"Blaster Master: Enemy Below",
		"Bomberman Max: Blue Champion",
		"Bomberman Max: Red Challenger",
		"Bomberman Quest",
		"Bugs Bunny: Crazy Castle 3",
		"Bugs Bunny in Crazy Castle 4",
		"Bust-A-Move 4 ",
		"Bust-A-Move Millennium ",
		"Cannon Fodder",
		"Centipede",
		"The Chessmaster",
		"Classic Bubble Bobble",
		"Conker's Pocket Tales",
		"Croc",
		"Croc 2",
		"Cruis'n Exotica",
		"Crystalis",
		"Daffy Duck: Fowl Play",
		"John Romero's Daikatana",
		"Deja Vu I & II",
		"Dexter's Laboratory: Robot Rampage ",
		"Disney's Donald Duck: Goin' Quackers",
		"Donkey Kong Country ",
		"Disney's Doug: Doug's Big Game",
		"Dragon Ball Z: Legendary Super Warriors",
		"Dragon Dance ",
		"Dragon Warrior I & II ",
		"Dragon Warrior III ",
		"Dragon Warrior Monsters",
		"Dragon Warrior Monsters 2: Cobi's Journey",
		"Dragon Warrior Monsters 2: Tara's Adventure",
		"Dragon's Lair",
		"Driver: You Are the Wheelman",
		"Duke Nukem",
		"Earthworm Jim: Menace 2 the Galaxy",
		"ECW Hardcore Revolution",
		"Disney's The Emperor's New Groove",
		"FIFA 2000",
		"Frogger",
		"Frogger 2: Swampy's Revenge",
		"Galaga: Destination Earth",
		"Game & Watch Gallery 2",
		"Game & Watch Gallery 3",
		"Gex: Enter the Gecko",
		"Gex 3: Deep Pocket Gecko",
		"Ghosts 'n Goblins",
		"Grand Theft Auto",
		"Grand Theft Auto 2",
		"The Grinch",
		"Halloween Racer",
		"Hamtaro: Ham-Hams Unite!",
		"Hands of Time",
		"Harry Potter and the Chamber of Secrets",
		"Harry Potter and the Sorcerer's Stone",
		"Harvest Moon GBC",
		"Harvest Moon GBC 2",
		"Harvest Moon GBC 3",
		"Heroes of Might and Magic",
		"Heroes of Might and Magic II",
		"Hexcite: The Shapes of Victory",
		"Hole in One Golf",
		"Indiana Jones and the Infernal Machine",
		"International Superstar Soccer 99",
		"International Superstar Soccer 2000",
		"Walt Disney's The Jungle Book: Mowgli's Wild Adventure",
		"Ken Griffey Jr.'s Slugfest",
		"Kirby Tilt 'n' Tumble ",
		"Legend of the River King GBC",
		"Legend of the River King 2",
		"The Legend of Zelda: Link's Awakening DX",
		"The Legend of Zelda: Oracle of Ages",
		"The Legend of Zelda: Oracle of Seasons",
		"LEGO Racers",
		"Disney's The Lion King: Simba's Mighty Adventure",
		"Looney Tunes",
		"Looney Tunes: Carrot Crazy",
		"Looney Tunes: Twouble!",
		"Looney Tunes Collector: Alert!",
		"Lucky Luke",
		"Lucky Luke: Desperado Train",
		"Lufia: The Legend Returns ",
		"Madden NFL 2000",
		"Madden NFL 2001",
		"Madden NFL 2002",
		"Magi Nation",
		"Magical Drop",
		"Magical Tetris Challenge",
		"Mario Golf",
		"Mario Tennis",
		"Marvin Strikes Back!",
		"Mat Hoffman's Pro BMX",
		"Mega Man Xtreme ",
		"Mega Man Xtreme 2 ",
		"Metal Gear Solid ",
		"Metal Walker",
		"Mickey's Racing Adventure",
		"Mickey's Speedway USA",
		"Micro Machines 1 and 2: Twin Turbo",
		"Micro Machines V3",
		"Midway Presents Arcade Hits: Joust & Defender",
		"Midway Presents Arcade Hits: Moon Patrol & Spy Hunter",
		"Missile Command",
		"Monkey Puncher",
		"Monopoly",
		"Monster Rancher Battle Card GB",
		"Monster Rancher Explorer ",
		"Disney-Pixar Monsters, Inc.",
		"Mortal Kombat 4",
		"Motocross Maniacs 2 ",
		"Mr. Driller",
		"Mr. Nutz",
		"Ms. Pac-Man: Special Color Edition",
		"The Mummy",
		"NASCAR 2000",
		"NBA 3-on-3 Featuring Kobe Bryant",
		"NBA Hoopz",
		"NBA In the Zone",
		"NBA In the Zone 2000",
		"NBA Jam 99",
		"NBA Jam 2001",
		"NFL Blitz 2001",
		"NHL 2000",
		"NHL Blades of Steel 2000",
		"Oddworld Adventures 2",
		"Pac-Man: Special Color Edition",
		"Perfect Dark",
		"Pocket Bomberman",
		"Pokemon Crystal Version",
		"Pokemon Gold Version ",
		"Pokemon Pinball",
		"Pokemon Puzzle Challenge",
		"Pokemon Silver Version ",
		"Pokemon Trading Card Game",
		"Power Quest",
		"Saban's Power Rangers: Lightspeed Rescue",
		"Saban's Power Rangers: Time Force",
		"Prince of Persia",
		"Project S-11",
		"Puzzle Master",
		"Q*bert",
		"Quest: Brian's Journey",
		"Rampart",
		"Rayman",
		"Rayman 2: The Great Escape",
		"Razor Freestyle Scooter",
		"Resident Evil Gaiden",
		"Return of the Ninja",
		"Revelations: The Demon Slayer ",
		"Road Rash",
		"Roadsters",
		"Robopon: Sun Version",
		"R-Type DX",
		"Scooby-Doo! Classic Creep Capers",
		"Shadowgate Classic",
		"Shantae",
		"The Smurfs Nightmare",
		"Snoopy Tennis",
		"Space Invaders",
		"Space Station Silicon Valley",
		"Spawn",
		"Spider-Man",
		"Spider-Man 2: The Sinister Six",
		"Spy vs. Spy",
		"Star Wars Episode I: Racer",
		"Street Fighter Alpha: Warriors' Dreams",
		"Super Breakout!",
		"Super Mario Bros. Deluxe",
		"Survival Kids",
		"SWIV",
		"Disney's Tarzan",
		"Test Drive Le Mans",
		"Tetris DX",
		"Tiny Toon Adventures: Buster Saves the Day",
		"Toki Tori",
		"Tom and Jerry",
		"Tom and Jerry in Mouse Attacks!",
		"Tom Clancy's Rainbow Six",
		"Tomb Raider",
		"Tomb Raider: Curse of the Sword",
		"Tony Hawk's Pro Skater",
		"Tony Hawk's Pro Skater 2",
		"Tony Hawk's Pro Skater 3",
		"Top Gear Pocket",
		"Top Gear Pocket 2",
		"Disney-Pixar Toy Story Racer",
		"Turok: Rage Wars",
		"Turok 2: Seeds of Evil",
		"Turok 3: Shadow of Oblivion",
		"Uno",
		"Vigilante 8",
		"V-Rally: Championship Edition",
		"Wacky Races",
		"Wario Land II",
		"Wario Land 3",
		"Warlocked",
		"Warriors of Might and Magic",
		"WCW Mayhem",
		"Wendy: Every Witch Way",
		"Woody Woodpecker Racing",
		"Worms Armageddon",
		"WWF Attitude",
		"WWF Betrayal",
		"WWF WrestleMania 2000",
		"X-Men: Mutant Academy",
		"X-Men: Mutant Wars",
		"X-Men: Wolverine's Rage",
		"Xtreme Sports",
		"Yars' Revenge",
		"Yu-Gi-Oh! Dark Duel Stories"
	],
	
	gba: [
		"007: Everything or Nothing",
		"007: Nightfire",
		"Activision Anthology",
		"Advance Guardian Heroes",
		"Advance Wars",
		"Advance Wars 2: Black Hole Rising",
		"Aero the Acro-Bat",
		"AirForce Delta Storm ",
		"Disney's Aladdin",
		"Alien Hominid",
		"Altered Beast: Guardian of the Realms",
		"American Bass Challenge ",
		"Astro Boy: Omega Factor",
		"Atari Anniversary Advance",
		"Baldur's Gate: Dark Alliance",
		"Ballistic: Ecks vs. Sever ",
		"Banjo-Kazooie: Grunty's Revenge",
		"Banjo-Pilot",
		"Baseball Advance",
		"Batman: Rise of Sin Tzu",
		"Batman: Vengeance",
		"Batman Begins",
		"Battle B-Daman",
		"Battle B-Daman: Fire Spirits!",
		"Beyblade G-Revolution",
		"Blackthorne",
		"Blades of Thunder",
		"Blender Bros.",
		"Boktai: The Sun Is in Your Hand",
		"Boktai 2: Solar Boy Django",
		"Bomberman Max 2: Blue Advance",
		"Bomberman Max 2: Red Advance",
		"Bomberman Tournament ",
		"Boulder Dash EX",
		"Breath of Fire",
		"Breath of Fire II",
		"Broken Sword: The Shadow of the Templars",
		"Bruce Lee: Return of the Legend",
		"Bubble Bobble: Old & New",
		"Capcom Classics Mini Mix",
		"Car Battler Joe",
		"Castlevania: Aria of Sorrow",
		"Castlevania: Circle of the Moon",
		"Castlevania: Harmony of Dissonance",
		"Centipede, Breakout & Warlords",
		"ChuChu Rocket!",
		"CIMA: The Enemy ",
		"Classic NES Series: Bomberman",
		"Classic NES Series: Castlevania",
		"Classic NES Series: Donkey Kong",
		"Classic NES Series: Dr. Mario",
		"Classic NES Series: Excitebike",
		"Classic NES Series: Ice Climber",
		"Classic NES Series: Metroid",
		"Classic NES Series: Pac-Man",
		"Classic NES Series: Super Mario Bros.",
		"Classic NES Series: The Legend of Zelda",
		"Classic NES Series: Xevious",
		"Classic NES Series: Zelda II: The Adventure of Link",
		"Columns Crown",
		"Comix Zone",
		"Contra Advance: The Alien Wars EX ",
		"Crash Bandicoot: The Huge Adventure",
		"Crash Bandicoot 2: N-Tranced",
		"Crash Bandicoot Purple: Ripto's Rampage",
		"Crash Nitro Kart",
		"Crazy Taxi: Catch a Ride",
		"CT Special Forces",
		"CT Special Forces 2: Back in the Trenches",
		"CT Special Forces 3: Bioterror",
		"Dark Arena",
		"DemiKids: Dark Version ",
		"DemiKids: Light Version ",
		"Denki Blocks!",
		"Desert Strike Advance",
		"Digimon Battle Spirit",
		"Digimon Battle Spirit 2",
		"Digimon Racing",
		"Dinotopia: The Timestone Pirates",
		"DK: King of Swing",
		"Dokapon: Monster Hunter",
		"Donald Duck Advance",
		"Donkey Kong Country ",
		"Donkey Kong Country 2 ",
		"Donkey Kong Country 3 ",
		"Doom",
		"Doom II",
		"Double Dragon Advance",
		"Dr. Mario & Puzzle League",
		"Dragon Ball: Advanced Adventure",
		"Dragon Ball GT: Transformation",
		"Dragon Ball Z: Buu's Fury",
		"Dragon Ball Z: Collectible Card Game",
		"Dragon Ball Z: Supersonic Warriors",
		"Dragon Ball Z: The Legacy of Goku",
		"Dragon Ball Z: The Legacy of Goku II",
		"Drill Dozer",
		"Driv3r",
		"Driver 2 Advance",
		"Drome Racers",
		"Dual Blades",
		"Duel Masters: Kaijudo Showdown",
		"Duel Masters: Sempai Legends",
		"Duel Masters: Shadow of the Code",
		"Duke Nukem Advance",
		"Dungeons & Dragons: Eye of the Beholder",
		"Dynasty Warriors Advance",
		"Earthworm Jim",
		"Earthworm Jim 2",
		"Ecks vs. Sever",
		"Egg Mania",
		"Family Feud",
		"FIFA Soccer 07",
		"Final Fantasy I & II: Dawn of Souls",
		"Final Fantasy IV Advance",
		"Final Fantasy Tactics Advance",
		"Final Fantasy V Advance",
		"Final Fantasy VI Advance",
		"Final Fight One",
		"Fire Emblem",
		"Fire Emblem: The Sacred Stones",
		"Fire Pro Wrestling",
		"Fire Pro Wrestling 2",
		"Fortress",
		"Frogger Advance: The Great Quest",
		"Frogger Adventures: Temple of the Frog",
		"Frogger Adventures 2: The Lost Wand",
		"Frogger's Journey: The Forgotten Relic",
		"F-Zero: GP Legend",
		"F-Zero: Maximum Velocity",
		"Gadget Racers ",
		"Game & Watch Gallery 4",
		"Garfield and His Nine Lives",
		"Gauntlet: Dark Legacy",
		"Gauntlet & Rampart",
		"Gekido Advance: Kintaro's Revenge",
		"Gem Smashers",
		"Ghost Rider",
		"Godzilla: Domination!",
		"Golden Sun",
		"Golden Sun: The Lost Age",
		"Gradius Galaxies",
		"Grand Theft Auto Advance",
		"GT Advance: Championship Racing",
		"GT Advance 2: Rally Racing",
		"GT Advance 3: Pro Concept Racing",
		"Guilty Gear X: Advance Edition",
		"Gumby vs. the Astrobots",
		"Gunstar Super Heroes",
		"Hamtaro: Ham-Ham Games",
		"Hamtaro: Ham-Ham Heartbreak",
		"Hamtaro: Rainbow Rescue",
		"Harry Potter: Quidditch World Cup",
		"Harry Potter and the Chamber of Secrets",
		"Harry Potter and the Goblet of Fire",
		"Harry Potter and the Order of the Phoenix",
		"Harry Potter and the Prisoner of Azkaban",
		"Harry Potter and the Sorcerer's Stone",
		"Harvest Moon: Friends of Mineral Town",
		"Harvest Moon: More Friends of Mineral Town",
		"The Hobbit: The Prelude to The Lord of the Rings",
		"I Spy Challenger!",
		"Ice Nine",
		"The Incredible Hulk",
		"The Incredibles",
		"International Superstar Soccer",
		"International Superstar Soccer Advance",
		"Invader",
		"Marvel's The Invincible Iron Man",
		"Iridion 3D",
		"Iridion II",
		"It's Mr. Pants",
		"Jackie Chan Adventures: Legend of the Dark Hand",
		"James Pond: Codename RoboCod",
		"Jazz Jackrabbit",
		"Jet Grind Radio ",
		"Walt Disney's The Jungle Book",
		"Jurassic Park III: Park Builder",
		"Justice League Heroes: The Flash",
		"Karnaaj Rally",
		"Kill.Switch",
		"Disney's Kim Possible: Revenge of Monkey Fist",
		"Disney's Kim Possible 2: Drakken's Demise",
		"Disney's Kim Possible 3: Team Possible",
		"The King of Fighters EX: Neo Blood",
		"The King of Fighters EX2: Howling Blood",
		"Kingdom Hearts: Chain of Memories",
		"Kirby: Nightmare in Dream Land",
		"Kirby & the Amazing Mirror",
		"Klonoa: Empire of Dreams",
		"Klonoa 2: Dream Champ Tournament",
		"Konami Collector's Series: Arcade Advanced",
		"Konami Krazy Racers",
		"Kuru Kuru Kururin",
		"Lady Sia",
		"The Legend of Spyro: A New Beginning",
		"The Legend of Spyro: The Eternal Night",
		"The Legend of Zelda: A Link to the Past & Four Swords",
		"The Legend of Zelda: The Minish Cap",
		"LEGO Bionicle",
		"LEGO Racers 2",
		"LEGO Star Wars: The Video Game",
		"LEGO Star Wars II: The Original Trilogy",
		"Disney's Lilo & Stitch",
		"Disney's Lilo & Stitch 2: Haemsterviel Havoc",
		"Disney's The Lion King 1 1/2",
		"The Lord of the Rings: The Fellowship of the Ring",
		"The Lord of the Rings: The Return of the King",
		"The Lord of the Rings: The Third Age",
		"The Lord of the Rings: The Two Towers",
		"The Lost Vikings",
		"Lucky Luke: Wanted!",
		"Lufia: The Ruins of Lore ",
		"Lunar Legend",
		"Disney's Magical Quest Starring Mickey & Minnie",
		"Disney's Magical Quest 2 Starring Mickey & Minnie",
		"Disney's Magical Quest 3 Starring Mickey & Donald",
		"Manic Miner",
		"Marble Madness & Klax",
		"Mario & Luigi: Superstar Saga ",
		"Mario Golf: Advance Tour",
		"Mario Kart: Super Circuit",
		"Mario Party Advance",
		"Mario Pinball Land",
		"Mario Tennis: Power Tour",
		"Mario vs. Donkey Kong",
		"Marvel: Ultimate Alliance",
		"Max Payne",
		"Mazes of Fate",
		"Mech Platoon",
		"Medabots: Metabee Version",
		"Medabots: Rokusho Version",
		"Medabots AX: Metabee Ver.",
		"Medabots AX: Rokusho Ver.",
		"Medal of Honor: Infiltrator",
		"Mega Man & Bass ",
		"Mega Man Battle Chip Challenge",
		"Mega Man Battle Network",
		"Mega Man Battle Network 2",
		"Mega Man Battle Network 3: Blue Version",
		"Mega Man Battle Network 3: White Version",
		"Mega Man Battle Network 4: Blue Moon",
		"Mega Man Battle Network 4: Red Sun",
		"Mega Man Battle Network 5: Team Colonel",
		"Mega Man Battle Network 5: Team Protoman",
		"Mega Man Battle Network 6: Cybeast Falzar",
		"Mega Man Battle Network 6: Cybeast Gregar",
		"Mega Man Zero",
		"Mega Man Zero 2",
		"Mega Man Zero 3",
		"Mega Man Zero 4",
		"Metal Slug Advance",
		"Metroid: Zero Mission",
		"Metroid Fusion",
		"Micro Machines",
		"Midway's Greatest Arcade Hits",
		"Millipede, Super Breakout & Lunar Lander",
		"Mobile Suit Gundam SEED: Battle Assault",
		"Monopoly",
		"Monster Force",
		"Monster House",
		"Monster Rancher Advance",
		"Monster Rancher Advance 2",
		"Monster Truck Madness",
		"Mortal Kombat: Deadly Alliance",
		"Mortal Kombat: Tournament Edition",
		"Mortal Kombat Advance",
		"Moto Racer Advance",
		"Motocross Maniacs Advance",
		"MotoGP",
		"Mr. Driller 2",
		"Mr. Nutz",
		"Ms. Pac-Man: Maze Madness",
		"Namco Museum",
		"Namco Museum: 50th Anniversary",
		"Shonen Jump's Naruto: Ninja Council",
		"Shonen Jump's Naruto: Ninja Council 2",
		"NBA Jam 2002",
		"Need for Speed: Most Wanted",
		"Need for Speed: Porsche Unleashed",
		"Need for Speed: Underground",
		"Need for Speed: Underground 2",
		"Need for Speed Carbon: Own the City",
		"Tim Burton's The Nightmare Before Christmas: The Pumpkin King",
		"Ninja Five-O ",
		"Oddworld: Munch's Oddysee",
		"Shonen Jump's One Piece",
		"Onimusha Tactics",
		"Pac-Man Collection",
		"Pac-Man World",
		"Pac-Man World 2",
		"Paperboy & Rampage",
		"Phalanx",
		"Phantasy Star Collection",
		"Pinball Advance",
		"The Pinball of the Dead",
		"Pinobee: Wings of Adventure",
		"Pirates of the Caribbean: Dead Man's Chest",
		"Pirates of the Caribbean: The Curse of the Black Pearl",
		"Pitfall: The Lost Expedition",
		"Planet Monsters",
		"Pocky & Rocky with Becky ",
		"Pokemon Emerald Version",
		"Pokemon FireRed Version",
		"Pokemon LeafGreen Version",
		"Pokemon Mystery Dungeon: Red Rescue Team",
		"Pokemon Pinball: Ruby & Sapphire",
		"Pokemon Ruby Version",
		"Pokemon Sapphire Version",
		"Polarium Advance",
		"Pong, Asteroids & Yars' Revenge",
		"Prehistorik Man",
		"Prince of Persia: The Sands of Time",
		"Puyo Pop",
		"Puyo Pop Fever",
		"Racing Gears Advance",
		"Rave Master: Special Attack Force!",
		"Rayman: Hoodlum's Revenge",
		"Rayman: Raving Rabbids",
		"Rayman 3: Hoodlum Havoc",
		"Rayman Advance",
		"Rebelstar: Tactical Command",
		"The Revenge of Shinobi",
		"River City Ransom EX ",
		"Riviera: The Promised Land",
		"Road Rash: Jailbreak",
		"Road Trip: Shifting Gears ",
		"Robopon 2: Cross Version",
		"Robopon 2: Ring Version",
		"Robotech: The Macross Saga",
		"Rock n' Roll Racing",
		"R-Type III: The Third Lightning",
		"Sabre Wulf",
		"Samurai Deeper Kyo",
		"Samurai Jack: The Amulet of Time",
		"Scooby-Doo! Mystery Mayhem",
		"The Scorpion King: Sword of Osiris",
		"Scurge: Hive",
		"SD Gundam Force",
		"Sega Arcade Gallery",
		"Sega Smash Pack",
		"Shonen Jump's Shaman King: Legacy of Spirits - Soaring Hawk",
		"Shonen Jump's Shaman King: Legacy of Spirits - Sprinting Wolf",
		"Shonen Jump's Shaman King: Master of Spirits",
		"Shonen Jump's Shaman King: Master of Spirits 2",
		"Shining Force: Resurrection of the Dark Dragon",
		"Shining Soul",
		"Shining Soul II",
		"Shrek 2",
		"Sigma Star Saga",
		"Silent Scope",
		"SimCity 2000",
		"The Simpsons: Road Rage",
		"The Sims 2",
		"The Sims 2: Pets",
		"The Sims Bustin' Out",
		"Smashing Drive",
		"Snood",
		"Snood 2: On Vacation",
		"Sonic Advance",
		"Sonic Advance 2",
		"Sonic Advance 3",
		"Sonic Battle",
		"Sonic Pinball Party",
		"Sonic the Hedgehog Genesis",
		"Space Channel 5: Ulala's Cosmic Attack",
		"Space Invaders",
		"Spider-Man",
		"Spider-Man 2",
		"Spider-Man 3",
		"Spider-Man: Battle for New York",
		"Spider-Man: Mysterio's Menace",
		"Spirits & Spells ",
		"SpongeBob Squarepants: Battle for Bikini Bottom",
		"Spy Hunter",
		"Spy Hunter & Super Sprint",
		"Spyro: Attack of the Rhynocs",
		"Spyro: Season of Ice",
		"Spyro 2: Season of Flame",
		"Spyro Orange: The Cortex Conspiracy",
		"Star Wars: The New Droid Army",
		"Star Wars Episode I: Jedi Power Battles",
		"Star Wars Episode II: Attack of the Clones",
		"Star Wars Episode III: Revenge of the Sith",
		"Star Wars Trilogy: Apprentice of the Force",
		"Star X",
		"Steel Empire",
		"Street Fighter Alpha 3",
		"Stuntman",
		"Summon Night: Swordcraft Story",
		"Summon Night: Swordcraft Story 2",
		"Super Army War ",
		"Super Bust-A-Move ",
		"Super Dodge Ball Advance",
		"Super Ghouls 'n Ghosts",
		"Super Mario Advance",
		"Super Mario Advance 2: Super Mario World",
		"Super Mario Advance 3: Yoshi's Island",
		"Super Mario Advance 4: Super Mario Bros. 3",
		"Super Monkey Ball Jr.",
		"Super Puzzle Fighter II",
		"Super Robot Taisen: Original Generation",
		"Super Robot Taisen: Original Generation 2",
		"Super Street Fighter II Turbo: Revival",
		"Sword of Mana ",
		"Tactics Ogre: The Knight of Lodis",
		"Tak: The Great Juju Challenge",
		"Tak 2: The Staff of Dreams",
		"Tak and the Power of Juju",
		"Tales of Phantasia",
		"Tang Tang",
		"Disney's Tarzan: Return to the Jungle",
		"Teen Titans",
		"Teen Titans 2",
		"Teenage Mutant Ninja Turtles",
		"Teenage Mutant Ninja Turtles 2: Battle Nexus",
		"Tekken Advance",
		"Terminator 3: Rise of the Machines",
		"Tetris Worlds",
		"Tiny Toon Adventures: Scary Dreams",
		"Tiny Toon Adventures: Wacky Stackers",
		"TMNT",
		"Tokyo Xtreme Racer Advance",
		"Tom Clancy's Rainbow Six: Rogue Spear",
		"Tom Clancy's Splinter Cell",
		"Tom Clancy's Splinter Cell: Pandora Tomorrow",
		"Tomb Raider: Legend",
		"Tomb Raider: The Prophecy",
		"Tony Hawk's American Sk8land",
		"Tony Hawk's Downhill Jam",
		"Tony Hawk's Pro Skater 2",
		"Tony Hawk's Pro Skater 3",
		"Tony Hawk's Pro Skater 4",
		"Tony Hawk's Underground",
		"Tony Hawk's Underground 2",
		"Top Gear Rally",
		"The Tower SP",
		"Tron 2.0: Killer App",
		"Turbo Turtle Adventure",
		"Turok: Evolution",
		"Tweety and the Magic Gems",
		"Ultimate Brain Games",
		"Ultimate Card Games",
		"Ultimate Muscle: The Kinnikuman Legacy - The Path of the Superhero",
		"Ultimate Spider-Man",
		"Uno 52",
		"Uno Free Fall",
		"The Urbz: Sims in the City",
		"Virtua Tennis",
		"Virtual Kasparov",
		"V-Rally 3",
		"Wade Hixton's Counter Punch",
		"Wario Land 4",
		"WarioWare: Twisted!",
		"WarioWare, Inc.: Mega Microgame$!",
		"Wing Commander: Prophecy",
		"Wings",
		"Wolfenstein 3D",
		"Woody Woodpecker in Crazy Castle 5",
		"Worms Blast",
		"Worms World Party",
		"WWE Road to WrestleMania X8",
		"WWE Survivor Series",
		"WWF Road to WrestleMania",
		"X-Men: Reign of Apocalypse",
		"X-Men: The Official Game",
		"X-Men 2: Wolverine's Revenge",
		"Yggdra Union: We'll Never Fight Alone",
		"Yoshi Topsy-Turvy",
		"Yu Yu Hakusho: Ghostfiles - Spirit Detective",
		"Yu Yu Hakusho: Ghostfiles - Tournament Tactics",
		"Yu-Gi-Oh! 7 Trials to Glory: World Championship Tournament 2005",
		"Yu-Gi-Oh! Destiny Board Traveler",
		"Yu-Gi-Oh! Dungeon Dice Monsters",
		"Yu-Gi-Oh! GX: Duel Academy",
		"Yu-Gi-Oh! Reshef of Destruction",
		"Yu-Gi-Oh! The Eternal Duelist Soul",
		"Yu-Gi-Oh! The Sacred Cards",
		"Yu-Gi-Oh! Ultimate Masters: World Championship Tournament 2006",
		"Yu-Gi-Oh! World Championship Tournament 2004",
		"Yu-Gi-Oh! Worldwide Edition: Stairway to the Destined Duel",
		"Zatch Bell! Electric Arena",
		"Zoids Legacy ",
		"Zone of the Enders: The Fist of Mars",
		"ZooCube",
		"Zooo: Action Puzzle Game"
	],
	
	mastersystem: [
		"Action Fighter",
		"The Addams Family",
		"Aerial Assault",
		"After Burner",
		"Air Rescue",
		"Disney's Aladdin",
		"Alex Kidd: High-Tech World",
		"Alex Kidd: The Lost Stars",
		"Alex Kidd in Miracle World",
		"Alex Kidd in Shinobi World",
		"Alien 3",
		"Alien Storm",
		"Alien Syndrome",
		"Altered Beast ",
		"Arcade Smash Hits",
		"Disney's Ariel the Little Mermaid",
		"Assault City",
		"Asterix",
		"Asterix and the Great Rescue",
		"Asterix and the Secret Mission",
		"Astro Warrior",
		"Ayrton Senna's Super Monaco GP II",
		"Aztec Adventure ",
		"Baku Baku Animal",
		"Bank Panic",
		"Batman Returns",
		"Battle OutRun",
		"Battletoads in Battlemaniacs",
		"Black Belt ",
		"Blade Eagle 3-D",
		"Bomber Raid",
		"Bonanza Bros.",
		"Disney's Bonkers Wax Up!",
		"Bubble Bobble",
		"Buggy Run",
		"California Games",
		"California Games II",
		"Captain Silver",
		"Castle of Illusion Starring Mickey Mouse",
		"Chase H.Q.",
		"Cheese Cat-Astrophe Starring Speedy Gonzales",
		"Choplifter",
		"Chuck Rock",
		"Chuck Rock II: Son of Chuck",
		"Cloud Master ",
		"Columns",
		"Cool Spot",
		"Cosmic Spacehead",
		"The Cyber Shinobi",
		"Cyborg Hunter",
		"Daffy Duck in Hollywood",
		"Danan: The Jungle Fighter",
		"Deep Duck Trouble Starring Donald Duck",
		"Desert Speedtrap Starring Road Runner and Wile E. Coyote",
		"Desert Strike: Return to the Gulf",
		"Double Dragon",
		"Double Hawk",
		"Dr. Robotnik's Mean Bean Machine",
		"Dragon Crystal",
		"Dynamite Duke",
		"Dynamite Dux",
		"Dynamite Headdy",
		"Earthworm Jim",
		"Ecco: The Tides of Time",
		"Ecco the Dolphin",
		"Enduro Racer",
		"ESWAT",
		"F1 ",
		"Fantastic Dizzy",
		"Fantasy Zone",
		"Fantasy Zone: The Maze",
		"Fantasy Zone II: The Tears of Opa-Opa",
		"Fire & Forget II",
		"The Flash",
		"Forgotten Worlds",
		"Gain Ground",
		"Galactic Protector",
		"Galaxy Force",
		"Gangster Town",
		"Gauntlet",
		"Ghost House",
		"Ghostbusters",
		"Ghouls 'n Ghosts ",
		"Global Defense ",
		"G-LOC: Air Battle",
		"Golden Axe",
		"Golden Axe Warrior",
		"Golfamania",
		"Golvellius: Valley of Doom",
		"GP Rider",
		"Great Baseball",
		"Great Soccer ",
		"Hang-On",
		"The Incredible Hulk",
		"Indiana Jones and the Last Crusade: The Action Game",
		"James Pond 007: The Duel",
		"James \"Buster\" Douglas Knockout Boxing ",
		"James Pond II: Codename RoboCod",
		"Joe Montana Football",
		"Disney's The Jungle Book",
		"Jurassic Park",
		"Kenseiden",
		"King's Quest: Quest for the Crown",
		"Klax",
		"Kung Fu Kid",
		"Land of Illusion Starring Mickey Mouse",
		"Legend of Illusion Starring Mickey Mouse",
		"Lemmings",
		"Line of Fire",
		"The Lion King",
		"Lord of the Sword",
		"The Lucky Dime Caper Starring Donald Duck",
		"Marble Madness",
		"Master of Darkness ",
		"Masters of Combat",
		"Maze Hunter 3-D",
		"Megumi Rescue",
		"Mercs",
		"Michael Jackson's Moonwalker",
		"Mickey's Ultimate Challenge",
		"Micro Machines",
		"Miracle Warriors: Seal of the Dark Lord",
		"Missile Defense 3-D",
		"Monopoly",
		"Montezuma's Revenge Featuring Panama Joe",
		"Mortal Kombat",
		"Mortal Kombat II",
		"Mortal Kombat 3",
		"Ms. Pac-Man",
		"My Hero",
		"The New Zealand Story",
		"The Ninja",
		"Ninja Gaiden",
		"Olympic Gold: Barcelona '92",
		"Operation Wolf",
		"OutRun",
		"OutRun 3-D",
		"OutRun Europa",
		"Pac-Mania",
		"Paperboy",
		"Penguin Land",
		"Phantasy Star",
		"Pit Pot ",
		"Populous",
		"Poseidon Wars 3-D",
		"Power Strike",
		"Power Strike II",
		"Predator 2",
		"Prince of Persia",
		"Pro Wrestling",
		"Psychic World",
		"Psycho Fox",
		"Putt & Putter",
		"Quartet",
		"Quest for the Shaven Yak Starring Ren & Stimpy",
		"R.C. Grand Prix",
		"Rainbow Islands",
		"Rambo: First Blood Part II",
		"Rambo III",
		"Rampage",
		"Rampart",
		"Rastan",
		"Renegade",
		"Rescue Mission",
		"Road Rash",
		"RoboCop versus The Terminator",
		"R-Type",
		"Sagaia ",
		"Satellite 7",
		"Scramble Spirits",
		"Sega Chess",
		"Sensible Soccer: European Champions",
		"Shadow Dancer: The Secret of Shinobi",
		"Shadow of the Beast",
		"Shanghai",
		"Shinobi",
		"Shooting Gallery",
		"Slap Shot",
		"The Smurfs",
		"Snail Maze",
		"Sonic Blast",
		"Sonic Chaos ",
		"Sonic Spinball",
		"Sonic the Hedgehog",
		"Sonic the Hedgehog 2",
		"Space Gun",
		"Space Harrier",
		"Space Harrier 3-D",
		"Special Criminal Investigation ",
		"SpellCaster ",
		"Spider-Man vs. The Kingpin",
		"Spy vs. Spy",
		"Star Wars",
		"Street Fighter II'",
		"Streets of Rage",
		"Streets of Rage 2",
		"Strider",
		"Strider II",
		"Submarine Attack",
		"Super Monaco GP",
		"Super Off Road",
		"Super Space Invaders",
		"Super Tennis ",
		"T2: The Arcade Game",
		"Taz-Mania",
		"Tecmo World Cup '93",
		"Teddy Boy",
		"The Terminator",
		"Terminator 2: Judgment Day",
		"Thunder Blade",
		"Time Soldiers",
		"Tom and Jerry: The Movie",
		"TransBot ",
		"Ultima IV: Quest of the Avatar",
		"Ultimate Soccer",
		"Vigilante",
		"Virtua Fighter Animation",
		"Wanted",
		"Where in the World Is Carmen Sandiego?",
		"Wimbledon",
		"Wimbledon II",
		"Winter Olympic Games: Lillehammer '94",
		"Wonder Boy",
		"Wonder Boy III: The Dragon's Trap",
		"Wonder Boy in Monster Land",
		"Wonder Boy in Monster World",
		"Woody Pop ",
		"World Class Leaderboard Golf",
		"World Cup USA 94",
		"World Grand Prix",
		"WWF WrestleMania Steel Cage Challenge",
		"Xenon 2: Megablast",
		"X-Men: Mojo World",
		"Ys: The Vanished Omens",
		"Zaxxon 3-D",
		"Zillion",
		"Zillion II: The Tri Formation",
		"Zool: Ninja of the \"Nth\" Dimension"
	],
	
	genesis: [
		"688 Attack Sub",
		"Aaahh!!! Real Monsters",
		"The Addams Family",
		"The Adventures of Batman & Robin",
		"Aero the Acro-Bat",
		"Aero the Acro-Bat 2",
		"Aerobiz",
		"Aerobiz Supersonic",
		"After Burner II",
		"Air Buster ",
		"Air Diver",
		"Disney's Aladdin",
		"Disney's Aladdin: Final Cut",
		"Alex Kidd in the Enchanted Castle",
		"Alien 3",
		"Alien Soldier",
		"Alien Storm",
		"Alisia Dragoon",
		"Altered Beast ",
		"Animaniacs",
		"Arcus Odyssey ",
		"Disney's Ariel the Little Mermaid",
		"Arrow Flash",
		"Art of Fighting",
		"Asterix and the Power of the Gods",
		"Atomic Runner ",
		"ATP Tour Championship Tennis",
		"Ayrton Senna's Super Monaco GP II",
		"B.O.B.",
		"Ballz 3D",
		"Bass Masters Classic: Pro Edition",
		"Batman: The Video Game",
		"Batman Returns",
		"Battle Master",
		"Battletech: A Game of Armored Combat",
		"Battletoads",
		"Battletoads & Double Dragon: The Ultimate Team",
		"Beavis and Butt-Head",
		"The Berenstain Bears' Camping Adventure",
		"Beyond Oasis ",
		"Bill Walsh College Football",
		"Bill Walsh College Football 95",
		"Bimini Run",
		"Bio-Hazard Battle",
		"Blades of Vengeance",
		"Blaster Master 2",
		"Bloodshot ",
		"Bonanza Brothers",
		"Boogerman: A Pick and Flick Adventure",
		"Boxing Legends of the Ring ",
		"Bram Stoker's Dracula",
		"Brian Lara Cricket",
		"Brian Lara Cricket 96",
		"Brutal: Paws of Fury",
		"Bubba 'n' Stix",
		"Bubble and Squeak",
		"Bubsy II",
		"Bubsy in Claws Encounters of the Furred Kind",
		"Buck Rogers: Countdown to Doomsday",
		"Bugs Bunny in Double Trouble",
		"Bulls versus Blazers and the NBA Playoffs",
		"Bulls versus Lakers and the NBA Playoffs",
		"Burning Force",
		"Cadash",
		"Cannon Fodder",
		"Captain America and the Avengers",
		"Castle of Illusion Starring Mickey Mouse",
		"Castlevania: Bloodlines ",
		"Centurion: Defender of Rome",
		"Chakan: The Forever Man",
		"Champions World Class Soccer",
		"Championship Bowling",
		"Championship Pro-Am ",
		"Chase H.Q. II",
		"Cheese Cat-Astrophe Starring Speedy Gonzales",
		"Chiki Chiki Boys ",
		"Chuck Rock",
		"Chuck Rock II: Son of Chuck",
		"ClayFighter",
		"Coach K College Basketball",
		"College Football USA 96",
		"College Football USA 97",
		"College Football's National Championship",
		"College Football's National Championship II",
		"College Slam",
		"Columns",
		"Columns III: Revenge of Columns",
		"Combat Cars",
		"Comix Zone",
		"Contra: Hard Corps ",
		"Cool Spot",
		"Cosmic Spacehead",
		"Crack Down",
		"Crue Ball: Heavy Metal Pinball",
		"Crusader of Centy ",
		"Cyborg Justice",
		"Darius",
		"Dashin' Desperadoes",
		"Davis Cup Tennis",
		"Daze Before Christmas",
		"The Death and Return of Superman",
		"Decap Attack ",
		"Demolition Man",
		"Desert Demolition Starring Road Runner and Wile E. Coyote",
		"Desert Strike: Return to the Gulf",
		"Devilish: The Next Possession",
		"Dick Tracy",
		"Tom Mason's Dinosaurs for Hire",
		"Donald in Maui Mallard",
		"Doom Troopers",
		"Double Dribble: The Playoff Edition",
		"Dr. Robotnik's Mean Bean Machine",
		"Dragon's Fury ",
		"Dragon's Revenge",
		"Dune: The Battle for Arrakis",
		"Dungeons & Dragons: Warriors of the Eternal Sun",
		"Dynamite Duke",
		"Dynamite Headdy",
		"Earthworm Jim",
		"Earthworm Jim 2",
		"Ecco: The Tides of Time",
		"Ecco Jr.",
		"Ecco the Dolphin",
		"El Viento",
		"Elemental Master",
		"ESPN Baseball Tonight",
		"ESPN National Hockey Night",
		"ESWAT: City Under Siege",
		"Eternal Champions",
		"Evander Holyfield's \"Real Deal\" Boxing",
		"Exile",
		"Ex-Mutants",
		"F1 World Championship Edition",
		"F-15 Strike Eagle II",
		"F-22 Interceptor",
		"F-117 Night Storm",
		"The Faery Tale Adventure",
		"Family Feud",
		"Fantastic Dizzy",
		"Fatal Fury ",
		"Fatal Fury 2 ",
		"Fatal Labyrinth",
		"Fatal Rewind ",
		"FIFA 98: Road to World Cup",
		"FIFA International Soccer",
		"FIFA Soccer 95",
		"FIFA Soccer 96",
		"FIFA Soccer 97",
		"Final Zone",
		"Fire Shark",
		"Flashback: The Quest for Identity",
		"Flicky",
		"Flink",
		"The Flintstones",
		"Forgotten Worlds",
		"Formula One",
		"Frogger",
		"Gadget Twins",
		"Gaiares",
		"Gain Ground",
		"Galahad ",
		"Galaxy Force II",
		"Garfield: Caught in the Act",
		"Gargoyles",
		"Gauntlet IV",
		"Gemfire ",
		"General Chaos",
		"Generations Lost",
		"Genghis Khan II: Clan of the Gray Wolf",
		"Ghostbusters",
		"Ghouls 'n Ghosts ",
		"G-LOC: Air Battle",
		"Gods",
		"Golden Axe",
		"Golden Axe II",
		"Granada",
		"The Great Circus Mystery Starring Mickey & Minnie ",
		"Greatest Heavyweights",
		"Greendog: The Beached Surfer Dude!",
		"Grind Stormer ",
		"Growl ",
		"Gunstar Heroes",
		"Haunting Starring Polterguy",
		"Hellfire",
		"Herzog Zwei",
		"High Seas Havoc ",
		"Home Alone",
		"Hook",
		"Hurricanes",
		"The Immortal",
		"The Incredible Hulk",
		"Insector X",
		"International Superstar Soccer Deluxe",
		"Jack Nicklaus' Power Challenge Golf",
		"James Pond: Underwater Agent",
		"James Pond II: Codename RoboCod",
		"James Pond 3: Operation Starfish",
		"Jerry Glanville's Pigskin Footbrawl",
		"Jewel Master",
		"Joe & Mac",
		"Joe Montana Football",
		"Joe Montana II: Sports Talk Football",
		"John Madden Football",
		"John Madden Football '92",
		"John Madden Football '93",
		"John Madden Football '93: Championship Edition",
		"Jordan vs. Bird",
		"Judge Dredd",
		"Disney's The Jungle Book",
		"Jungle Strike: The Sequel to Desert Strike",
		"Jurassic Park",
		"Jurassic Park: Rampage Edition",
		"Kawasaki Superbike Challenge",
		"Kid Chameleon",
		"King of the Monsters",
		"King of the Monsters 2",
		"King Salmon: The Big Catch",
		"King's Bounty: The Conqueror's Quest",
		"Klax",
		"Krusty's Super Fun House",
		"Lakers versus Celtics and the NBA Playoffs",
		"Landstalker: The Treasures of King Nole",
		"Last Battle",
		"Lemmings",
		"Lemmings 2: The Tribes",
		"Lethal Enforcers",
		"Lethal Enforcers II: Gun Fighters",
		"Liberty or Death",
		"Light Crusader",
		"Lightening Force: Quest for the Darkstar ",
		"The Lion King",
		"The Lost Vikings",
		"The Lost World: Jurassic Park",
		"Lotus II",
		"Lotus Turbo Challenge",
		"M.U.S.H.A.: Metallic Uniframe Super Hyrbid Armor ",
		"Madden NFL '94",
		"Madden NFL 95",
		"Madden NFL 96",
		"Madden NFL 97",
		"Madden NFL 98",
		"Scholastic's The Magic School Bus: Space Exploration Game",
		"Marble Madness",
		"Mario Andretti Racing",
		"Marvel Land ",
		"Master of Monsters",
		"Mazin Saga: Mutant Fighter",
		"McDonald's Treasure Land Adventure",
		"Mega Bomberman",
		"Mega Man: The Wily Wars ",
		"Mega SWIV ",
		"Mega Turrican",
		"Mercs",
		"Michael Jackson's Moonwalker",
		"Mick & Mack as the Global Gladiators",
		"Mickey Mania: The Timeless Adventures of Mickey Mouse",
		"Mickey's Ultimate Challenge",
		"Micro Machines",
		"Micro Machines: Turbo Tournament 96",
		"Micro Machines 2: Turbo Tournament",
		"Micro Machines Military",
		"Midnight Resistance",
		"Might and Magic II: Gates to Another World",
		"Mighty Morphin Power Rangers",
		"Mighty Morphin Power Rangers: The Movie",
		"Minnsota Fats: Pool Legend",
		"MLBPA Baseball",
		"Monopoly",
		"Monster World IV",
		"Mortal Kombat",
		"Mortal Kombat II",
		"Mortal Kombat 3",
		"Mr. Nutz",
		"Ms. Pac-Man",
		"Mutant League Football",
		"Mutant Legacy Hockey",
		"Mystic Defender ",
		"Mystical Fighter",
		"NBA Action '94",
		"NBA Action '95 Starring David Robinson",
		"NBA Hang Time",
		"NBA Jam",
		"NBA Jam: Tournament Edition",
		"NBA Live 95",
		"NBA Live 96",
		"NBA Live 97",
		"NBA Live 98",
		"NBA Showdown '94",
		"Newman/Haas IndyCar Featuring Nigel Mansell",
		"NFL '95",
		"NFL 98",
		"NFL Football '94 Starring Joe Montana",
		"NFL Quarterback Club",
		"NFL Quarterback Club '96",
		"NFL Sports Talk Football '93 Starring Joe Montana",
		"NHL '94",
		"NHL 95",
		"NHL 96",
		"NHL 97",
		"NHL 98",
		"NHL All-Star Hockey 95",
		"NHL Hockey",
		"NHLPA Hockey 93",
		"Nigel Mansell's World Championship Racing",
		"Nobunaga's Ambition",
		"Olympic Gold: Barcelona '92",
		"The Ooze",
		"Operation Europe: Path to Victory 1939-45",
		"The Ottifants",
		"Out of This World ",
		"Outlander",
		"OutRun",
		"OutRun 2019",
		"OutRunners",
		"P.T.O.: Pacific Theater of Operations",
		"Pac-Attack",
		"Pac-Man 2: The New Adventures",
		"Pac-Mania",
		"Paperboy",
		"Paperboy 2",
		"Pebble Beach Golf Links",
		"Pete Sampras Tennis",
		"PGA European Tour",
		"PGA Tour 96",
		"PGA Tour Golf",
		"PGA Tour Golf II",
		"PGA Tour Golf III",
		"Phantasy Star II",
		"Phantasy Star III: Generations of Doom",
		"Phantasy Star IV: The End of the Millennium",
		"Phantom 2040",
		"Phelios",
		"Disney's Pinocchio",
		"The Pirates of Dark Water",
		"Pirates! Gold",
		"Pitfall: The Mayan Adventure",
		"Pit-Fighter",
		"Disney's Pocahontas",
		"Populous II: Two Tribes",
		"Power Drive",
		"Power Monger",
		"Powerball",
		"Predator 2",
		"Premier Manager 97",
		"Primal Rage",
		"Prime Time NFL Starring Deion Sanders",
		"Prince of Persia",
		"Prince of Persia (Mega Drive version)",
		"Psycho Pinball",
		"Puggsy",
		"The Punisher",
		"QuackShot Starring Donald Duck",
		"R.B.I. Baseball 3",
		"R.B.I. Baseball 4",
		"R.B.I. Baseball '93",
		"R.B.I. Baseball '94",
		"Radical Rex",
		"Raiden Trad ",
		"Rambo III",
		"Rampart",
		"Ranger X",
		"Red Zone",
		"The Ren & Stimpy Show Presents Stimpy's Invention",
		"The Revenge of Shinobi ",
		"Rings of Power",
		"Risk",
		"Risky Woods",
		"Ristar",
		"Road Rash",
		"Road Rash II",
		"Road Rash 3: Tour de Force",
		"RoadBlasters",
		"RoboCop versus The Terminator",
		"Rock n' Roll Racing",
		"Rocket Knight Adventures",
		"Rolling Thunder 2",
		"Rolling Thunder 3",
		"Rolo to the Rescue",
		"Romance of the Three Kingdoms II",
		"Romance of the Three Kingdoms III: Dragon of Destiny",
		"S.S. Lucifer: Man Overboard!",
		"Sagaia ",
		"Saint Sword",
		"Sampras Tennis 96",
		"Samurai Shodown ",
		"Saturday Night Slam Masters ",
		"Scooby-Doo Mystery",
		"Second Samurai",
		"Sensible Soccer: International Edition",
		"Shadow Blasters",
		"Shadow Dancer: The Secret of Shinobi",
		"Shadow of the Beast",
		"Shadow of the Beast II",
		"Shadowrun",
		"Shanghai II: Dragon's Eye",
		"Shaq-Fu",
		"Shining Force",
		"Shining Force II",
		"Shining in the Darkness",
		"Shinobi III: Return of the Ninja Master ",
		"Shove It! ...The Warehouse Game",
		"Side Pocket",
		"The Simpsons: Bart's Nightmare",
		"Skeleton Krew",
		"Skitchin'",
		"The Smurfs",
		"The Smurfs Travel the World",
		"Snake Rattle 'n' Roll",
		"Socket ",
		"Sol-Deace",
		"Soldiers of Fortune ",
		"Sonic & Knuckles",
		"Sonic & Knuckles (Blue Sphere)",
		"Sonic & Knuckles (Knuckles the Echidna in Sonic the Hedgehog 2)",
		"Sonic & Knuckles (Sonic the Hedgehog 3 & Knuckles)",
		"Sonic 3D Blast",
		"Sonic Spinball",
		"Sonic the Hedgehog",
		"Sonic the Hedgehog 2",
		"Sonic the Hedgehog 3",
		"Sorcerer's Kingdom",
		"Space Harrier II",
		"Space Invaders '91 ",
		"Sparkster",
		"Speedball 2: Brutal Deluxe",
		"Spider-Man: The Animated Series",
		"Spider-Man and the X-Men in Arcade's Revenge",
		"Spider-Man and Venom: Maximum Carnage",
		"Spider-Man and Venom: Separation Anxiety",
		"Spider-Man vs. The Kingpin",
		"Splatterhouse 2",
		"Splatterhouse 3",
		"Sports Talk Baseball",
		"Spot Goes to Hollywood",
		"Star Trek: Deep Space Nine - Crossroads of Time",
		"Star Trek: The Next Generation - Echoes from the Past",
		"Starflight",
		"Stargate",
		"Steel Empire",
		"Street Fighter II': Special Champion Edition",
		"Street Racer",
		"Streets of Rage",
		"Streets of Rage 2",
		"Streets of Rage 3",
		"Strider",
		"Strider Returns: Journey from Darkness ",
		"Striker",
		"Sub-Terrania",
		"Sunset Riders",
		"Super Baseball 2020",
		"Garry Kitchen's Super Battletank: War in the Gulf",
		"Super Fantasy Zone",
		"Super Hang-On",
		"Super Hydlide",
		"Super Monaco GP",
		"Super Skidmarks",
		"Super Smash T.V.",
		"Super Street Fighter II",
		"Super Volleyball",
		"Superman",
		"Sword of Vermilion",
		"Syd of Valis ",
		"Sylvester and Tweety in Cagey Capers",
		"Syndicate",
		"T2: The Arcade Game",
		"Disney's TaleSpin",
		"Target Earth ",
		"Taz in Escape from Mars",
		"Taz-Mania",
		"Team USA Basketball",
		"Technoclash",
		"Tecmo Super Baseball",
		"Tecmo Super Bowl",
		"Tecmo Super Bowl II: Special Edition",
		"Tecmo Super Bowl III: Final Edition",
		"Tecmo Super Hockey",
		"Tecmo Super NBA Basketball",
		"Teenage Mutant Ninja Turtles: The Hyperstone Heist",
		"Teenage Mutant Ninja Turtles: Tournament Fighters",
		"The Terminator",
		"Terminator 2: Judgment Day",
		"Tetris",
		"Theme Park",
		"Thunder Force II",
		"Thunder Force III",
		"The Tick",
		"Tinhead",
		"Tiny Toon Adventures: ACME All-Stars",
		"Tiny Toon Adventures: Buster's Hidden Treasure",
		"Todd's Adventures in Slime World",
		"ToeJam & Earl",
		"ToeJam & Earl in Panic on Funkotron",
		"Toki: Going Ape Spit",
		"Tom and Jerry: Frantic Antics!",
		"Tommy Lasorda Baseball ",
		"Top Gear 2",
		"Toughman Contest",
		"Disney's Toy Story",
		"Traysia",
		"Triple Play: Gold Edition",
		"Triple Play 96",
		"Trouble Shooter ",
		"True Lies",
		"Truxton ",
		"Turbo OutRun",
		"Twin Cobra: Desert Attack Helicopter ",
		"Twin Hawk ",
		"Two Crude Dudes",
		"Tyrants: Fight Through Time ",
		"Ultimate Mortal Kombat 3",
		"Ultimate Qix ",
		"Ultimate Soccer",
		"Uncharted Waters",
		"Uncharted Waters: New Horizons",
		"Urban Strike: The Sequel to Jungle Strike",
		"Valis ",
		"Valis III",
		"Vapor Trail",
		"Vectorman",
		"Vectorman 2",
		"Viewpoint",
		"Virtua Fighter 2",
		"Virtua Racing",
		"Virtual Bart",
		"Virtual Pinball",
		"VR Troopers",
		"Wardner",
		"Warlock",
		"Warsong ",
		"Weaponlord",
		"Wheel of Fortune",
		"Where in the World Is Carmen Sandiego?",
		"Whip Rush",
		"Williams Arcade's Greatest Hits",
		"Wimbledon Championship Tennis",
		"Wings of Wor ",
		"Wiz 'n' Liz",
		"Wolfchild",
		"Wolverine: Adamantium Rage",
		"Wonder Boy III: Monster Lair",
		"Wonder Boy in Monster World",
		"World Championship Soccer",
		"World Championship Soccer II",
		"World Class Leaderboard Golf",
		"World Heroes",
		"World of Illusion Starring Mickey Mouse and Donald Duck",
		"World Series Baseball",
		"World Series Baseball '95",
		"World Series Baseball '96",
		"World Series Baseball 98",
		"World Trophy Soccer",
		"Worms",
		"Wrestle War",
		"WWF Raw",
		"WWF Royal Rumble",
		"WWF Super WrestleMania",
		"WWF WrestleMania: The Arcade Game",
		"Xenon 2: Megablast",
		"X-Men",
		"X-Men 2: Clone Wars",
		"Ys III",
		"Zany Golf",
		"Zero the Kamikaze Squirrel",
		"Zero Tolerance",
		"Zero Wing",
		"Zombies Ate My Neighbors ",
		"Zool: Ninja of the \"Nth\" Dimension",
		"Zoom!",
		"Zoop"
	],
	
	gamegear: [
		"The Addams Family",
		"The Adventures of Batman & Robin",
		"Aerial Assault",
		"Disney's Aladdin",
		"Alien 3",
		"Alien Syndrome",
		"Arcade Classics",
		"Arena: Maze of Death",
		"Disney's Ariel the Little Mermaid",
		"Asterix and the Great Rescue",
		"Asterix and the Secret Mission",
		"Ax Battler: A Legend of Golden Axe",
		"Ayrton Senna's Super Monaco GP II",
		"Baku Baku Animal",
		"Batman Returns",
		"Battleship: The Classic Naval Combat Game",
		"Battletoads",
		"The Berenstain Bears' Camping Adventure",
		"Disney's Bonkers Wax Up!",
		"Bubble Bobble",
		"Bugs Bunny in Double Trouble",
		"Bust-A-Move ",
		"C.J. Elephant Fugitive",
		"Captain America and the Avengers",
		"Castle of Illusion Starring Mickey Mouse",
		"Chakan: The Forever Man",
		"Chase H.Q.",
		"Cheese Cat-Astrophe Starring Speedy Gonzales",
		"The Chessmaster",
		"Choplifter III",
		"Chuck Rock",
		"Chuck Rock II: Son of Chuck",
		"Columns",
		"Cool Spot",
		"Cosmic Spacehead",
		"Crystal Warriors ",
		"Daffy Duck in Hollywood",
		"Deep Duck Trouble Starring Donald Duck",
		"Defenders of Oasis",
		"Desert Speedtrap Starring Road Runner and Wile E. Coyote",
		"Desert Strike: Return to the Gulf",
		"Devilish",
		"Double Dragon",
		"Dr. Robotnik's Mean Bean Machine",
		"Dragon Crystal",
		"Dynamite Headdy",
		"Earthworm Jim",
		"Ecco: The Tides of Time",
		"Ecco the Dolphin",
		"Evander Holyfield's \"Real Deal\" Boxing",
		"The Excellent Dizzy Collection",
		"F1 World Championship Edition",
		"F-15 Strike Eagle",
		"Factory Panic",
		"Fantastic Dizzy",
		"Fantasy Zone",
		"Fatal Fury Special ",
		"FIFA International Soccer",
		"Galaga 2 ",
		"Garfield: Caught in the Act",
		"G-LOC: Air Battle",
		"GP Rider",
		"Halley Wars",
		"Hook",
		"The Incredible Hulk",
		"Iron Man and X-O Manowar in Heavy Metal",
		"James Bond 007: The Duel",
		"James Pond II: Codename RoboCod",
		"James Pond 3: Operation Starfish",
		"Joe Montana Football",
		"Judge Dredd",
		"Disney's The Jungle Book",
		"Jungle Strike: The Sequel to Desert Strike",
		"Jurassic Park",
		"Klax",
		"Land of Illusion Starring Mickey Mouse",
		"Legend of Illusion Starring Mickey Mouse",
		"Lemmings",
		"The Lion King",
		"The Lost World: Jurassic Park",
		"The Lucky Dime Caper Starring Donald Duck",
		"Madden NFL 95",
		"Magical Puzzle Popils",
		"The Majors: Pro Baseball",
		"Marble Madness",
		"Mega Man",
		"Mickey's Ultimate Challenge",
		"Micro Machines",
		"Micro Machines 2: Turbo Tournament",
		"Mighty Morphin Power Rangers",
		"Mighty Morphin Power Rangers: The Movie",
		"MLBPA Baseball",
		"Mortal Kombat",
		"Mortal Kombat II",
		"Mortal Kombat 3",
		"Ms. Pac-Man",
		"NBA Jam",
		"NBA Jam: Tournament Edition",
		"NHL All-Star Hockey",
		"NHL Hockey",
		"Ninja Gaiden",
		"Olympic Gold: Barcelona '92",
		"OutRun",
		"OutRun Europa",
		"Pac-Attack",
		"Pac-Man",
		"Paperboy",
		"Paperboy 2",
		"Pengo",
		"Phantom 2040",
		"Pinball Dreams",
		"Power Strike II ",
		"Predator 2",
		"Primal Rage",
		"Prince of Persia",
		"Psychic World",
		"Putt & Putter",
		"Quest for the Shaven Yak Starring Ren & Stimpy",
		"R.B.I. Baseball '94",
		"R.C. Grand Prix",
		"Revenge of Drancon ",
		"Ristar",
		"Road Rash",
		"RoboCop versus The Terminator",
		"Samurai Shodown ",
		"Sensible Soccer: European Champions",
		"Shaq-Fu",
		"Shining Force II: The Sword of Hajya ",
		"Shinobi ",
		"Shinobi II: The Silent Fury ",
		"Side Pocket",
		"Slider ",
		"Sonic Blast",
		"Sonic Chaos ",
		"Sonic Drift 2",
		"Sonic Labyrinth",
		"Sonic Spinball",
		"Sonic the Hedgehog",
		"Sonic the Hedgehog 2",
		"Sonic the Hedgehog: Tripe Trouble ",
		"Space Harrier",
		"Spider-Man: Return of the Sinister Six",
		"Spider-Man and the X-Men in Arcade's Revenge",
		"Spider-Man vs. The Kingpin",
		"Star Trek: The Next Generation - The Advanced Holodeck Tutorial",
		"Star Trek Generations: Beyond the Nexus",
		"Star Wars",
		"Streets of Rage ",
		"Streets of Rage 2 ",
		"Strider Returns: Journey from Darkness",
		"Garry Kitchen's Super Battletank: War in the Gulf",
		"Super Columns",
		"Super Monaco GP",
		"Super Off Road",
		"Super Space Invaders",
		"Super Star Wars: Return of the Jedi",
		"Tails Adventure",
		"Disney's TaleSpin",
		"Tempo Jr.",
		"Tesserae",
		"Tom and Jerry: The Movie",
		"True Lies",
		"Ultimate Soccer",
		"Urban Strike: The Sequel to Jungle Strike",
		"Vampire: Master of Darkness",
		"Virtua Fighter Animation ",
		"Winter Olympic Games: Lillehammer '94",
		"Wonder Boy III: The Dragon's Trap ",
		"Woody Pop",
		"World Class Leaderboard Golf",
		"World Cup USA 94",
		"World Series Baseball",
		"World Series Baseball '95",
		"WWF Raw",
		"WWF WrestleMania Steel Cage Challenge",
		"X-Men",
		"X-Men: Gamesmaster's Legacy",
		"X-Men: Mojo World",
		"Zool: Ninja of the \"Nth\" Dimension",
		"Zoop"
	],
	
	tg16: [
		"Aero Blasters ",
		"Air Zonk",
		"Alien Crush",
		"Andre Panza Kick Boxing",
		"Ballistix",
		"Battle Royale",
		"Blazing Lazers ",
		"Bloody Wolf",
		"Bomberman",
		"Bomberman '93",
		"Bonk III: Bonk's Big Adventure",
		"Bonk's Adventure",
		"Bonk's Revenge",
		"Boxy Boy ",
		"Bravoman",
		"Cadash",
		"Chase H.Q.",
		"Chew Man Fu ",
		"China Warrior ",
		"Cratermaze ",
		"Cyber-Core",
		"Dead Moon",
		"Deep Blue",
		"Devil's Crush ",
		"Double Dungeons",
		"Dragon Spirit",
		"Dragon's Curse ",
		"Drop Off",
		"Dungeon Explorer",
		"Dungeons & Dragons: Order of the Griffon",
		"Fantasy Zone",
		"Final Lap Twin",
		"Galaga '90 ",
		"Ghost Manor",
		"Hit the Ice: The Official Video Hockey League",
		"J.J. & Jeff ",
		"Jackie Chan's Action Kung Fu",
		"Keith Courage in Alpha Zones ",
		"King of Casino",
		"Klax",
		"Legend of Hero Tonma",
		"The Legendary Axe ",
		"The Legendary Axe II ",
		"Magical Chase",
		"Military Madness ",
		"Moto Roader",
		"Neutopia",
		"Neutopia II",
		"New Adventure Island ",
		"Ninja Spirit ",
		"Ordyne",
		"Pac-Land",
		"Parasol Stars: The Story of Bubble Bobble III",
		"Power Golf",
		"Psychosis ",
		"Raiden",
		"R-Type",
		"Samurai Ghost ",
		"Shockman ",
		"Side Arms: Hyper Dyne",
		"Silent Debuggers",
		"Sinistron ",
		"Soldier Blade",
		"Somer Assault ",
		"Space Harrier",
		"Splatterhouse",
		"Super Star Soldier",
		"Super Volleyball",
		"Disney's TaleSpin",
		"Tiger Road",
		"Time Cruise",
		"Timeball ",
		"Tricky Kick",
		"Turrican",
		"Veigues Tactical Gladiator",
		"Victory Run",
		"Vigilante",
		"World Class Baseball",
		"World Court Tennis"
	],
	
	neogeo: [
		"3 Count Bount ",
		"Aero Fighters 2 ",
		"Aero Fighters 3 ",
		"Alpha Mission II ",
		"Andros Dunos",
		"Art of Fighting ",
		"Art of Fighting 2 ",
		"Art of Fighting 3: The Path of the Warrior ",
		"Baseball Stars 2",
		"Blazing Star",
		"Blue's Journey ",
		"Bomberman: Panic Bomber",
		"Breakers",
		"Burning Fight",
		"Bust-A-Move ",
		"Captain Tomaday",
		"Crossed Swords",
		"Cyber-Lip",
		"Double Dragon",
		"Eight Man",
		"Far East of Eden: Kabuki Klash ",
		"Fatal Fury: King of Fighters ",
		"Fatal Fury 2 ",
		"Fatal Fury 3: Road to the Final Victory ",
		"Fatal Fury Special ",
		"Galaxy Fight: Universal Warriors",
		"Garou: Mark of the Wolves",
		"Ghost Pilots",
		"Karnov's Revenge ",
		"The King of Fighters '94",
		"The King of Fighters '95",
		"The King of Fighters '96",
		"The King of Fighters '97",
		"The King of Fighters '98: The Slugfest",
		"The King of Fighters '99: Millennium Battle",
		"The King of Fighters 2000",
		"The King of Fighters 2001",
		"The King of Fighters 2002",
		"The King of Fighters 2003",
		"King of the Monsters",
		"King of the Monsters 2",
		"Kizuna Encounter: Super Tag Battle",
		"The Last Blade",
		"The Last Blade 2",
		"Last Resort",
		"League Bowling",
		"Magical Drop II",
		"Magical Drop III",
		"Magician Lord",
		"Matrimelee ",
		"Metal Slug",
		"Metal Slug 2",
		"Metal Slug 3",
		"Metal Slug 4",
		"Metal Slug 5",
		"Metal Slug X",
		"Mutation Nation",
		"NAM-1975",
		"Neo Bomberman",
		"Neo Turf Masters",
		"Nightmare in the Dark",
		"Ninja Commando",
		"Ninja Master's",
		"Over Top",
		"Prehistoric Isle 2",
		"Pulstar",
		"Rage of the Dragons",
		"Real Bout Fatal Fury ",
		"Real Bout Fatal Fury 2: The Newcomers ",
		"Real Bout Fatal Fury Special ",
		"Robo Army",
		"Samurai Shodown ",
		"Samurai Shodown II ",
		"Samurai Shodown III ",
		"Samurai Shodown IV: Amakusa's Revenge ",
		"Samurai Shodown V ",
		"Samurai Shodown V Special ",
		"Savage Reign",
		"Sengoku",
		"Sengoku 2",
		"Sengoku 3",
		"Shock Troopers",
		"Shock Troopers: 2nd Squad",
		"SNK vs. Capcom: SVC Chaos",
		"Soccer Brawl",
		"Spinmaster ",
		"Street Slam ",
		"Strikers 1945 Plus",
		"Super Baseball 2020",
		"Super Sidekicks",
		"Super Sidekicks 2: The World Championship",
		"Super Sidekicks 3: The Next Glory",
		"Thrash Rally",
		"Top Hunter: Roddy & Cathy",
		"Twinkle Star Sprites",
		"Viewpoint",
		"Voltage Fighter Gowcaizer",
		"Waku Waku 7",
		"Windjammers",
		"World Heroes",
		"World Heroes 2",
		"World Heroes 2 Jet",
		"World Heroes Perfect",
		"Zed Blade",
		"Zupapa!"
	]
	
}